# test_polocolo.py
# ---------------------------------------------------------------------------
# Test suite for Polocolo, parametrized over the named instances in instances.py.
#
# Groups:
#   4.1 KATs         -- reference vectors (Rust reference implementation) and
#                       self-derived vectors (permutation + sponge), including
#                       the reconstruction of the reference's deviating instances
#   4.2 Roundtrip    -- permutation_inv undoes permutation (and per-layer)
#   4.3 Consistency  -- determinism, distinct inputs -> distinct outputs, sizes
#   4.4 Derivation   -- m/R derivation reproduces Tables 1/5/7, sigma conditions,
#                       MDS matrices vs. the Appendix A.1 constraint programs,
#                       LUT/round constants vs. the shipped reference constants,
#                       exhaustive toy S-box, the low-addition MDS search
#   4.5 Misc         -- validation/errors, warnings
# ---------------------------------------------------------------------------

import warnings
from math import ceil, log2

import pytest
from sage.all import GF

from recommendations import ParamRecommendationWarning
from polocolo.hash import Polocolo
from polocolo.params import PolocoloParams, MDS
from polocolo.instances import (
    POLOCOLO_BLS12_381_SCALAR_T3,
    POLOCOLO_BLS12_381_SCALAR_T4,
    POLOCOLO_BLS12_381_SCALAR_T5,
    POLOCOLO_BLS12_381_SCALAR_T6,
    POLOCOLO_BLS12_381_SCALAR_T7,
    POLOCOLO_BLS12_381_SCALAR_T8,
    POLOCOLO_BLS12_381_SCALAR_T3_TIGHT,
    POLOCOLO_BLS12_381_SCALAR_T4_TIGHT,
    POLOCOLO_BLS12_381_SCALAR_T6_TIGHT,
    POLOCOLO_BLS12_381_SCALAR_T8_TIGHT,
    POLOCOLO_BN254_SCALAR_T3,
    POLOCOLO_BN254_SCALAR_T4,
    POLOCOLO_BN254_SCALAR_T5,
    POLOCOLO_BN254_SCALAR_T6,
    POLOCOLO_BN254_SCALAR_T7,
    POLOCOLO_BN254_SCALAR_T8,
    POLOCOLO_BN254_SCALAR_T3_TIGHT,
    POLOCOLO_BN254_SCALAR_T4_TIGHT,
    POLOCOLO_BN254_SCALAR_T6_TIGHT,
    POLOCOLO_BN254_SCALAR_T8_TIGHT,
)
from utils.complexities import uni_solve_comp
from utils.field import BLS12_381_SCALAR, BN254_SCALAR
from utils.lut import power_residue_lut, power_residue_sigma, sigma_conditions_hold
from utils.matrix import circulant, dl_m44_84_matrix, is_mds, low_addition_mds_matrix
from utils.sampler import XOFFieldElementSampler

INSTANCES = [
    ("BLS12_381_SCALAR_T3", POLOCOLO_BLS12_381_SCALAR_T3),
    ("BLS12_381_SCALAR_T4", POLOCOLO_BLS12_381_SCALAR_T4),
    ("BLS12_381_SCALAR_T5", POLOCOLO_BLS12_381_SCALAR_T5),
    ("BLS12_381_SCALAR_T6", POLOCOLO_BLS12_381_SCALAR_T6),
    ("BLS12_381_SCALAR_T7", POLOCOLO_BLS12_381_SCALAR_T7),
    ("BLS12_381_SCALAR_T8", POLOCOLO_BLS12_381_SCALAR_T8),
    ("BLS12_381_SCALAR_T3_TIGHT", POLOCOLO_BLS12_381_SCALAR_T3_TIGHT),
    ("BLS12_381_SCALAR_T4_TIGHT", POLOCOLO_BLS12_381_SCALAR_T4_TIGHT),
    ("BLS12_381_SCALAR_T6_TIGHT", POLOCOLO_BLS12_381_SCALAR_T6_TIGHT),
    ("BLS12_381_SCALAR_T8_TIGHT", POLOCOLO_BLS12_381_SCALAR_T8_TIGHT),
    ("BN254_SCALAR_T3", POLOCOLO_BN254_SCALAR_T3),
    ("BN254_SCALAR_T4", POLOCOLO_BN254_SCALAR_T4),
    ("BN254_SCALAR_T5", POLOCOLO_BN254_SCALAR_T5),
    ("BN254_SCALAR_T6", POLOCOLO_BN254_SCALAR_T6),
    ("BN254_SCALAR_T7", POLOCOLO_BN254_SCALAR_T7),
    ("BN254_SCALAR_T8", POLOCOLO_BN254_SCALAR_T8),
    ("BN254_SCALAR_T3_TIGHT", POLOCOLO_BN254_SCALAR_T3_TIGHT),
    ("BN254_SCALAR_T4_TIGHT", POLOCOLO_BN254_SCALAR_T4_TIGHT),
    ("BN254_SCALAR_T6_TIGHT", POLOCOLO_BN254_SCALAR_T6_TIGHT),
    ("BN254_SCALAR_T8_TIGHT", POLOCOLO_BN254_SCALAR_T8_TIGHT),
]
IDS = [name for name, _ in INSTANCES]

P_BLS12 = BLS12_381_SCALAR.p

# ---------------------------------------------------------------------------
# Reference data for the tests below, kept directly in this module:
#
#   * REFERENCE_PERMUTATION_OUTPUTS: permutation outputs of the eight BLS12
#     instances shipped with the reference implementation
#     (https://github.com/KAIST-CryptLab/Polocolo, plain/), generated by
#     compiling and running that Rust code unchanged on three fixed inputs
#     per instance ("counting" = (0, ..., t-1), "zeros" = 0^t,
#     "negative" = (-1, ..., -t)).
#   * REFERENCE_INSTANCES: the parameters those eight instances ACTUALLY use.
#     Only T4_TIGHT matches the paper; the others deviate (mistyped matrices,
#     non-recommended m, and three "chimeras" whose round constants were
#     generated with a different m than their S-box) -- see the overrides and
#     RUST_MDS3 / RUST_MDS6 below, and the note in polocolo/instances.py.
#   * REFERENCE_LUT_SAMPLES / REFERENCE_RC_ROW0: constants copied verbatim from
#     plain/polocolo_luts.rs and plain/polocolo_lins.rs, to pin the constant
#     derivation (sigma/LUT and round constants) against the reference.
#   * SELF_KATS: self-derived vectors from this repo implementation for all 20
#     paper instances (regression guard, not reference data).
# ---------------------------------------------------------------------------

# Permutation outputs of the shipped reference instances (inputs reconstructed
# from the label by the test).
REFERENCE_PERMUTATION_OUTPUTS = {
    "T3": {
        "counting": [
            0x177cf99affbfc1ede2ca1e95c9c9a62f56997481b6cfbe4edb2811134bd0f92,
            0x38db86f3879ec3ca747daf5e3af71ac919ce12b732fcec92146e6c694e7a8bd7,
            0x271593746005d04efffdc9ed92596c25a704404f9d96971006d34ba7dc135607,
        ],
        "zeros": [
            0x25aaa70faa65ba3c5e141015189793e30dccea0d6248b5f7d2ff9424cf422ed4,
            0x31892c42eee3335f2b1ead12ed154792934a90382b458e3f811036e95f68f37a,
            0x4caaf84271a608ffb3c809d1430a22134e93892b0fa96decd5cc7fb8d28eaff9,
        ],
        "negative": [
            0x24340bd8a0dd5b76b6189101bc9ad789e5f11e8db8486793b04c329a97bcb28f,
            0x472a8f8cdeabf8139c64c5c602100f829a82e4ec93fb2be89b68c94233d48388,
            0x5cdfd763b962725467da75ea00d4b2934d4fe93b8ab7c499903edf8d19d3ac,
        ],
    },
    "T3_TIGHT": {
        "counting": [
            0x578692908b81fb4b4a68415f3f09013e1b9baec8dd69f8f16bd023de3007596c,
            0x5ac9a196cc3a7023f5183ec43b112dfe5277629bdc047b6ec46749b929a16e35,
            0x264047cc4be81578d863dd73755940d50b4269106b1c58428dad2115505ba537,
        ],
        "zeros": [
            0x7066769b8bd8a346df11de13bf87ad59ba63cf6df258cf2924ae4fb33e0bd123,
            0x522def8f0039941552b47931369ce4ccf90bf5398116aacccdcf4fb27fd0c98f,
            0x29c89b685eef3c027e24415b56256572f757e1fd5933d2d3ecc2deb912b06084,
        ],
        "negative": [
            0x1d4a57de5114596f6437b93d28480b156e4cbf9bb8906175b18c6597360dd717,
            0x52e060e82dee0aef30d75adeed07fc09ae9b3473dd6856033c726fb8d8419fb7,
            0xd75ecb8a675c5b7dec0f268205d36b520a2bb0927c52976bde74a317f8a6606,
        ],
    },
    "T4": {
        "counting": [
            0x581e6eae235a01a7e1c92b3384bf9cadfac1d3ef9a963d88df914374b129776a,
            0x3b414459e106c978887b472d89447e9a74c0dc13c7585620b151c2d1b314bfde,
            0xf02b03c9aeaf681608aed1f7ba0736492ff6a77efea6cb25d0baaf5297b4e41,
            0x396344fa6159c0d5051698a0f11856fc64db2f889f1cf536f0897cff647da71b,
        ],
        "zeros": [
            0x418dd83585b541a1a7f06be018f7ee52351f34ad949f15159a1edb0b7fe8382d,
            0x631af68cc21ab84aa1e0cc042bba66c5c2765cf4ce6830dcac0e67cf12aafebb,
            0x182dc35a9a928b15d0e1bc6567bc9cee3ba22bb03034c6c871033ad578cd3204,
            0x110f3023ef45e960761473ab5041ba9dcef1c4bf6d07cd0034cbec27d2c911e1,
        ],
        "negative": [
            0x3907c08798946326484f1a477b7fdead68253ca2c01a4c3c0c18ac094cb31984,
            0x13ee7351acce94917ac25158cee8f9c0a6ecdfa47507506865a3bca7984f13b6,
            0x25f6b4118b9caa4d66e6576582424139245404fa7b9578b286132b33d12c8021,
            0x55c125e584b0f5490627438e26db6f614094e2bf66954906ea53ecfb48327bb9,
        ],
    },
    "T4_TIGHT": {
        "counting": [
            0x213abcc0d762c3199072dd66175b8bdc8b59ef8468cfc60ccfc2e1b1df7ed310,
            0x3b6ca99ccc19d6d4874e427a73888d1f47a73463884ad8743a4baf949e388cb,
            0x41ab36b65dec27a6da46c3ca99e73580f6305c32d911ce88e648b968675fdd78,
            0x689bbde3df12b6c0d0256c65f1554052497549fe07966a8214d02f9153e5b26f,
        ],
        "zeros": [
            0x9f4e16231c7a6e649a1879b1e00250fd61c272328c140753fe9c027f940c6c7,
            0x70b3f6570748b3017c5a7d6439c4bc84e0d33a44de0d825d00c32180fc978af2,
            0x1fd41c635f31ab07e3b0f730675e6c7b0d7216001f84bd4f086474df08d62525,
            0x34804d3e189b31be79f969008b96cf09fe26afb783017745a17ec0728da16283,
        ],
        "negative": [
            0x2b4ad5386ef8e3188ae976fffcf88b647378ae109f5168e872fb2c809f5bc5c1,
            0x44a237b4694d2fd71615fed303a43ce506112b65419a98d4e2dc74ec40d48a26,
            0x586fad234d7763cc1a222fbbb941489fca136e47afdd921c5c17076ed28d1385,
            0x2ab2ff11d2b4eeaa43dbdb9e70f1791aa50006f2f82b97b22cd138e3074ed144,
        ],
    },
    "T6": {
        "counting": [
            0x22330baaca919a9999821f41c6ea77f51cd5694520bc43e671b1b0116a226b39,
            0x68870db3f284d3742d2e5ec4718b9e4db3d95a07c7a0787849d1ac21883ad16a,
            0x211bbe02bdf845ec698c0cfba98beb7f9306eb4681143dac5af687fffbfb6ed3,
            0x6e81d169fcb8e6b8472f673a4318aadab00adfc689170d4b44adb8f4fde6677b,
            0x85501f11b98a54d091e146d9d1286e2dffed124b5468b68f93b6c282e71906f,
            0xc8fdf02cef30bb1ae6227268e1646630555564a670da62f533dd1227ba353c2,
        ],
        "zeros": [
            0x5c55e50643ac4fe3014c53ff84e44c3e634f207f5e5d1b24558835e35fd7ec42,
            0x32ea7f199eda04faf51916f712c2426ff6d85d6ed1d21dc1be2120488557e1d,
            0x3e44ad40467edcf1eaa2bf5980241f5eb7f3a5c8c4af6216dc5cc8c358edaa06,
            0x2cfae65183e708599ada676a62751d1ccac8cb4df4b54066c046fdde419661cc,
            0x308d25ec6308a368c30178f1a08d4c3336ce800dfdb50d30e6422177b37a4b08,
            0x616b89f7fa30b73955e1212ef4661220d443a79530ccb050108dc80943a94dc3,
        ],
        "negative": [
            0x20364e26c9dea61daa63d2b16e7a4b717f544e589b62708a33ddf3e11836413d,
            0x4ff2f843d99ce9cbe2a1ad24f0a31d89ffc801c250dc291f7dfc32e73f5cb1e2,
            0x64a7da2379dd3140c2f1622cc45d9492f5c774b30034ae3e8684c92a832d9872,
            0x34e4ed65b74d5cf9f2c4ce9341475351a6ae1c7a6ef3f7ac5a74778b3ea46958,
            0x61b53943cf0da63ac13fe763d3460384a265335547450e8b35f07b36ecea203a,
            0x1391ae69ef65e932e89eec8b92b89695cd4cf3e91629a1c0b6aef5bc6f1e0563,
        ],
    },
    "T6_TIGHT": {
        "counting": [
            0xf4ea6077bc2b041482ec390f37599c85c6351b87fccc866c6f82609e940fff0,
            0x4d61e4a7716bf646e6b1d219030931d61604767fdd7e55a71aac7625e1b6d754,
            0x2af50d219fd5ad6b8c235972c116d8bd1660809fe23e3aed97deab71c4bc299f,
            0x4c0a7b7a0f7ccb8ad631be99ab23bf1669b2337aa0746aefeb76d61ddd6b466f,
            0x6b97fa672a750b336ed09cf10aec867385b3feb116c6c3417ae9afae7d799269,
            0x58954d138b2e52e3baa8b2d93a277fcfba28f9cfeb9b3f1d32453f200dc927ac,
        ],
        "zeros": [
            0x6d75ac6d536d7e3bbc1ca3fa1803278b9c47c49ea3d0c75acbfd68e2c1e1646c,
            0x70fe23b5713380866d8504d5d62fc823e61356408955cd80de8b5a43b669f4fa,
            0x3295374f683123bbdd504188893a522045444b964a7a7ac770932bd27e7afc2f,
            0x3c078883d0d9fd6da13d567d43e19126a78ee5cc3907581c600b653208dff73d,
            0x4c7526a5c4cf257a90026bf4e052cdbc895fb87d61f0143a5ef627ec03fc75eb,
            0x35f31b9a4f4caa1c0356f12e675fa3e834a801e068c309be3d9844ea3d7269ec,
        ],
        "negative": [
            0xdd1121cbaaf970929d89625ae6825d4a7518bd7cdf4190b0ebfd8e0d80ece1f,
            0x1cd9ffa41544b51913b802f488419bdc0562a21fe765c1895e0b09b0a64b12da,
            0x179771eb07c7e15a353908cab51259e47b6c3086da5222f03396ace9a5a88649,
            0x198d57a6d05a587a4d77c2fcca0fd6eb405cb6a858bd4b40d4aecce43080921f,
            0x27cc8ebb3fb0b36880daaee3b112802fc3cfca159df45966b82321f5b357d3ec,
            0x15433d0973fe023a578b7a5744fb5b9cd7cb287316be27ae9841c84c01ccae59,
        ],
    },
    "T8": {
        "counting": [
            0x96a667e6f1c737e1a55b353e4dbe1f1b1ea43a46e96d3fdcc0751a52068d484,
            0x73dbfd26c99212c92b180d8df7ea57ca40cd3063383c1051a8b7ee55b6de8840,
            0x1be5140cd78c95c2594a22f6b0b4ba91d8017ac69c995efadbbb6ec982f951e3,
            0x56ce5822ab1fdefd2a1142c8c179f39d193b2b91005ae1337c566fb1248cc8ce,
            0x657cce0ba4b999b1de25ec24e4de8865b908201dc1b1a2db660902dbc69a1221,
            0x5067cc859b39fccdd6c933524806b2628865a835920c8682515ed45c920e2b04,
            0x57a8529211e74d45e335ab31105ebab08cb2548bc433cc10762203fba40f4f7b,
            0x540ea44730c71c2c8a28749bf6d01cee213f715c9c650a2b29e4ba3041f5937f,
        ],
        "zeros": [
            0x68536427b131af8d06f1349e00fabeb4354ec8a718ae41641f43f6c090dbab4e,
            0x53dc1f6e3bce7041e30de150b3d5681316a445845b6fd091714bb2780e6e408b,
            0x33106f118fb99e271a30e2ca84cafca8af904b8b02d0acbe26aca40faa8a0f8,
            0x52f7311650982db3f250ca811a4212bf1c1eef770b8cc361d69cb12698ca3138,
            0x1c390cb5007c908d67aaba0740461568029c6c1fdbf26590c1abc2452a2c95b9,
            0x6f54457d99f203645e1eec0d425e50ad9f77a2ca2dc62ddfe62c6ce5847f3dd7,
            0x1c32f0b8562a58ee671431d56a859f717e1dd367fa8f0c1889bd8be15913c6a0,
            0x4f082b180473fc8732664171841197cfcd6b37f1ba7fac4a05c35cc0fa8ea287,
        ],
        "negative": [
            0x6138cfa88455d5d4d92597cb77a3f9565edd22f9df5b708236b77a589483d669,
            0x30b888ce913e4a5ad2ccebdabd9502e8deb4d832524a6a2290ccffaeda6820fa,
            0x53071a474a398e0695ae920449185f97cc0ebddd6b7857f644e4616ee254c8a3,
            0x100a7371b4d81d877f139b5c25910d729bb1dfafc138bad512c7d93aa9ff2787,
            0x192aa1b654ec2254174a1b9dbfc2cb209bce24c35fad49ab284d33efa0d6015e,
            0x36b548684c848a799c0c870361a820ddcbe9f6d15dd091cd73ffed1b550a6361,
            0x984d04ad28998a5a1caa6b6ffc9818eea6c8d2796ac041372bced63cd999c33,
            0x547d8496ea0ad450c3abcbf1985a929a39609a470951a927bc6eb970d487359a,
        ],
    },
    "T8_TIGHT": {
        "counting": [
            0x61026e7657d72cb6ad823042fab4350957fcc4b5e937fd54ce7c3fa1e10c37b0,
            0x1eb8a59c93090b07de5f359e58e1d4f47684fc7861cc626d2879c8975c179805,
            0x58c68a03ab6fa76f188742d5b057a1ef8fbfe5689b05805eff1f239841e9485b,
            0x662156572ce94c9c7cf277a04323c4479c7d4069a72812ce0e1f22b2df5df29,
            0x3814fe8f7afd70e058454f142ba1366dd96b920b7005b80acfe76eee51453989,
            0xeb8d3412298551b5fd532473e98138d4d95366509977a3913edafcd34c9fe83,
            0x42dae52ecabbd0f3ea52e8ba7a7a46711641d0ce1a61e4442953c7d18c4374b0,
            0x5727028c285fa17bc1b4db125a2bccb7e7b200a997421cdd419e67ff7ef2e61e,
        ],
        "zeros": [
            0x3f6743a84906c760aa57e2b4a0ad158ac15f69551904c14081694c1e5c109833,
            0x4d160682b1f78933b3fc0db37e73e1a8e951db4c158c08878bbbbda6b777648e,
            0x4340a8650f213f16b40fc7d200cd26acfd779dd2f7e267ad9b6dcfc602af1d95,
            0x487f7b15c71880841db26ff34ac0af11afeb40aba26636fef24fa5483cb83303,
            0x10a0be60241caf4f4a46afef4277fba39c14efb077c8af7cca22df4c02105fa,
            0x26e5c88eb19cff346ea006d7e751628377f92f22bd2aabd3532df9d3bc234259,
            0x10ae04a931af33a56426ab4a1d3f6d3cb69cf51988fc9b15b5e0d29413381ab3,
            0x6b91383f63dfd902c9509c6b7362cad3acf88386647127cf6b1a2f723db38f5e,
        ],
        "negative": [
            0x467217fc43566f237b3f8fea6d09df1f97d908be9bb39416fb3fa78aeccecde7,
            0x36f0f0b6450938c4bd975eb4ebbcda11fc41aa4b2ce06911848d48613dac5fdd,
            0x101aaeff8516b97757f6fb5dae14fe73776752d12e2b0bbe424c396cc93ca73b,
            0x715bc74bc83848b99cd4e4dcbd8d6ddfb354317f835d0aff45a896903594d946,
            0x3043d97b103c371a75559ab1a92788462ef617e83a10d7bf2c033456a7eb83b8,
            0x31778051e7217149519c408fad146ed7173008bf67b263bbe7f70c0ba7e155b1,
            0x4a1024c0e769d2b21b9a4c8a968b68f8ff6f3c7f6544a067c09b1664deae767f,
            0x1a99d035d61b7179f69809ad99f0276c392279731ab4308596947e639d83f8e9,
        ],
    },
}

# The mistyped matrices of the reference (see polocolo/params.py: row 2 of its
# MDS3 is (1, 2, 2) -- not even MDS -- and its MDS6 has 4277 instead of 4227).
RUST_MDS3 = [[2, 1, 1], [1, 2, 2], [1, 1, 2]]
RUST_MDS6 = [[1011, 1470, 42, 140, 508, 1700], [232, 70, 48, 48, 264, 1280],
             [4277, 7371, 3, 490, 1420, 2900], [6744, 11760, 60, 844, 2272, 4670],
             [13281, 23163, 9, 1540, 4460, 9100], [48, 84, 12, 35, 40, 200]]

# (name, t, m of the S-box, R, MDS override or None, m of the round-constant seed
# where it differs from the S-box m -- the three chimeras -- or None)
REFERENCE_INSTANCES = [
    ("T3",       3, 1024, 6, RUST_MDS3, None),
    ("T3_TIGHT", 3, 1024, 5, RUST_MDS3, None),
    ("T4",       4, 1024, 5, None,      None),
    ("T4_TIGHT", 4, 1024, 4, None,      None),   # the only instance matching the paper
    ("T6",       6, 512,  5, RUST_MDS6, 128),
    ("T6_TIGHT", 6, 128,  4, RUST_MDS6, None),
    ("T8",       8, 128,  5, None,      32),
    ("T8_TIGHT", 8, 32,   4, None,      64),
]

# Sample entries {m: [(power residue, table value), ...]} of the shipped BLS12
# lookup tables (first, second and last non-zero entry of each LUT{m}).
REFERENCE_LUT_SAMPLES = {
    32: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x00000000000000000000000000000000000000000000000000287f3c1a5b27d7),
        (0x50e0903a157988bab4bcd40e22f55448bf6e88fb4c38fb8a360c60997369df4e,
         0x000000000000000000000000054b6aab673278f2ad8681e1e4610526a3f01477),
        (0x5e73ed8c432405d0ae25b21df6c52b2a6c7876bf0928e68fae34a81e1cfca2ec,
         0x2be171f4caf0654733da6a74d5a139f242a8b907cd0691ff927f956bf0a537c7),
    ],
    64: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x00000000000000000000000000000000000000000000000000000000000041a7),
        (0x45af6345ec055e4d14a1e27164d8fdbd2d967f4be2f951558140d032f0a9ee53,
         0x5e8359240dcdf810b2fbe9bea5d03ef529e769cd53cd52119fc3e1b52db7940b),
        (0x640d097461a2eeaf4e84b3cd7dc75b61db872ef3dce28e788d28c143168bba2c,
         0x50925d0dbcf1d1241c5032fadb3dd8df92d11e348fd5aea7863cc069a72d4c2b),
    ],
    128: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x0012e4f0085e2cdf4227aaa7129bc7b47f517bf145186bd31063ae9db20e8177),
        (0x6898111413588742b7c68b4d7fdd60d098d0caac87f5713c5130c2c1660125be,
         0x448a28ed5251cf3853005f882a68bc4d4528a9db8c9cfc5703c4b26ac6d0c593),
        (0x60c7efec34093e9a725ce48f79bf9cd60081066e578d78bf6207cd2f20df9d12,
         0x5a38a7c811b339501f9a92f64e6a5e0f04df66365dcc2ef8e92c2d20561676de),
    ],
    256: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x2f3e95142ae3289a07c57e99e82c396acc7bb3f49f5888286e2c48d653bbcfe2),
        (0x4f9b4098e2e9f12e6b368121ac0cf4ad0a0865a899e8deff4935bd2f817f694b,
         0x6ae034b911d84196bd519e68f3a45aa668e95b348ace653830ae5604cafde64a),
        (0x18ba7658084c71a467e701a945e9b713df7b4ee66e4caccb7d01866add958780,
         0x2204e288208874cece385327d99e9262404789e50ffde0876acf7dfa2a9b9b8e),
    ],
    512: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x0f960c14c67c6dc10074068fca82580db9c3bf1cd9f33d0437bcae06bbaa70d1),
        (0x095166525526a65439feec240d80689fd697168a3a6000fe4541b8ff2ee0434e,
         0x359212e01f14f1a8b9a1f49e542df43fca3d620f992cfac827aba6d80bfc214d),
        (0x6a61dbd781fc6d1c881dab49e15d37277dd34dc48b542a7916654b4e3193f385,
         0x61d6dbd21375d79204ef6895d8b98d8718c2ca51ae547bdc854cef0a20a3a284),
    ],
    1024: [
        (0x0000000000000000000000000000000000000000000000000000000000000001,
         0x398386ad9f180e19ab8a99cad81555f6c6a36c3fb8917ce1314aedcc0de8f7f1),
        (0x325db5c3debf77a18f4de02c0f776af3ea437f9626fc085e3c28d666a5c2d854,
         0x52a00002d4ea6147b7b0b64ea5692717146a7fb2458756beae1f07df7c688539),
        (0x5164ca4cf7456c9b942c20e45c3ad14d9ce862487904d0ab1b561347c6a47727,
         0x17f15674106c97f31ab2fda5adbff23582af7cf9f62d45efbf96a52c9ded2fb3),
    ],
}

# First round-constant row of each shipped RC table, keyed by (m, R, t) of the
# SHAKE128 seed "Polocolo-{m}-{R}-{t}-BLS12" (note the chimera m values).
REFERENCE_RC_ROW0 = {
    (1024, 6, 3): [
        0x09f0d43341118eeceebf0b080e95091903d3108651aa392880e8cad22b10f1a2,
        0x06220d2c73c88f8b8c8b0550bbee038257ebccccdb3c1df70f2c807de0941317,
        0x01a66aa6656154587d99c737d28b127a7a0c9de0f2818425489cd29f37caa730,
    ],
    (1024, 5, 3): [
        0x0a300647a00eacf1af5bf43abb053f7455f925d78d29c29777baa0f3c359de68,
        0x0623334148420a457ef004db8e9a2cde3d10ccf5424a429dbb2cf69cc0127c40,
        0x4bff344f2c8cdfac93bfd2bec8fed62cbb0e0865b7b8f382a438daf5a69c629b,
    ],
    (1024, 5, 4): [
        0x2b0eea5a41ad55f030befea2ae4fed2b2ba15614c8a64f26e0a4c8b30cff7c5e,
        0x651c4f7b98aa409e248fd9c04e5f840c97712a9437be6b9cc41e10d1539f3d0b,
        0x600b721ff0b66ca7f018fbf539a15dce22addd64b909d0ed41f6c70e362cbec7,
        0x61c9fa4202570ad089bd0e94ed2541f720003cb3f85d1d3586e41b0edb6d7991,
    ],
    (1024, 4, 4): [
        0x3b802bcf754924d09c82ff31b8825ec21879429d890fe769218e348c277ce017,
        0x455cab4032e3d97439da6b05ccf50bf75649cbbb61ab6aec2c677d39585dbd8c,
        0x165a1a535de59c5b295bc744d7a1e57b825a7e9d739f144e2ccdbddfba670f87,
        0x6fc366df2e7ee3f95b14f4b75816544a28b06f780ad9ce82b9d9e9d148db979a,
    ],
    (128, 5, 6): [
        0x0103834030f79804ae9c13e0b5aa4424c07a7948fb40598a482985cc661acc33,
        0x6a39fba6d4164bb8c4062ea61ceae6d7f2760b32aed4819877330424461dcb58,
        0x1d2f4684d45516f70d0241315cfc43aa2b5e5dfa8630382794c796343eee810d,
        0x0a92d081205d56936e4c8423966497d9365451e12e5d1d12f27740e337c17e5c,
        0x27317cfcc712b8205257a999f782747d48e0d3f21b6e6b7b6a7c63d57ad4a3c9,
        0x3bab28439a82f7ffd2b3826cc2bfebfa4e6e8880d0d601397009e96ada3e8464,
    ],
    (128, 4, 6): [
        0x688188a6e53a13a8afef13863d7e62156542eb24181dcc77e0d46130b98c4b34,
        0x3da441f8aecfa812424ee63968ba24e256865614e8191fb9b26f7a5f997d37e6,
        0x5d4ad241761331678249fc3df12d245aa54fce3df47ece595652ac15809c80fe,
        0x0058edd5a3fd5771e0960673b10a5c5f4fa10878f9d3dfaf6b907cc6ffa5e6d2,
        0x1fda8f445065f78199f961759b00f1743f86d6ad63ee79636a5571d0cf3f8afe,
        0x69543d9c5a58492c722b7f805208fe6d82261f7ea74c0faf14ae700674fbd79a,
    ],
    (32, 5, 8): [
        0x2c6006e0ef82c16382a7f1fc3e9c3ef9d70d364b48a43187f42549f4415d4223,
        0x4fbe60b62e77bad552526bc34037168e64f1417b459a4490300c0775f5676c2c,
        0x4afa19ab0ba5af3999a7df0a3742cfc5f36b13b6d8bcf13982cd09abdbc9827c,
        0x5f3354b1a2eab05e7e883e9d6291f909e3282ecc1640a2a6281e942f078e7c04,
        0x26cb80af9790797959fb4a2a58bb640f1dffb9bd50feebdfcd6e95de257d790b,
        0x4ad7972475371b36bb31bfbdde715c07aa1619ed22bbfed0e7070d91f4779705,
        0x2cc1f61796a49e693704c40d0ae0094f4f3f34a81159b1f3369441599d1cfa7f,
        0x0411cb74003b1962f5240bce85d035c871639c3fbbd04b78957f067dc4d49eda,
    ],
    (64, 4, 8): [
        0x1947b59eedb65080aaab80adbc9dd564871200a6f172c3977dcc673c04d7ba88,
        0x7050c4878040c55077b23165f57e8e5b05d696231657d46b5b7293050c283ef0,
        0x4ab3b460f913c6c95956fe185786e1e5f2d76bae74c24f1b54ca50368aaf69bd,
        0x73214627c1cc2d64aedbd7a83945d4014db7f8418a46da9e97a39859f735181a,
        0x4ce1b0ef223595802c75727a71988a7b1f51bf49012aaca7a041c9e1f681e6de,
        0x5fbe2b86a1a3c72a4502615771b24ea2a2fc0de31f99be4ad02da6b148d06d54,
        0x2de0dea3c68ac49fe7a2d0e16372d37649864aff0495aa270d60f9a6f8d8788b,
        0x2213632a5a4d5e80b56d4f848d278b30dcfa1116c70fb00e6cac80241a0abb99,
    ],
}

# ---------------------------------------------------------------------------
# Self-derived KATs for all 20 paper instances (bootstrapped by running this
# repo implementation once; guards against regressions, not against a
# wrong-but-self-consistent implementation -- that is what the reference data
# above is for).
# ---------------------------------------------------------------------------
SELF_KATS = {
    "BLS12_381_SCALAR_T3": {
        "permutation": [
            {"input": [0, 0, 0],
             "output": [
                0x3468a2829c5a7706c33d35ea39ffb57408b23f30e1de365f8d4c30f52af1f8c6,
                0x641b40704517e4ed97daec2d137aad90c0dc7074c57759bb4d2f22a9b4b366fa,
                0x726cbf55bb6a12127daa2309ef2800372cbe8c2df93be16333a62447096f997e,
            ]},
            {"input": [0, 1, 2],
             "output": [
                0x21e0eb9f8c874252d318ea09da39db619f834ccdf33fc4c6dcd8d597298a8f3a,
                0x534f58bba32cac7ce1da1b24bc6c9ed32393ce839db01e71cb3e6a1e0fd38c4,
                0x2072a60abeeab8b515a98069d1ea08cd5cbde63177e728c6d5dacb9df54b997d,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x3037a0257f3153a60ca43db71f10c05b60627ea1b2e6cbd2bdd7492dfe78f9c1,
            ]},
            {"input": [1, 2],
             "output": [
                0x4da041b4c9a811368f08e7a81ed6e28f23c6e5735915e0ac1855871bcb4cf982,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T3_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0],
             "output": [
                0x663bc1176cde6b453a554ab7fa663bac18869f81eff16f3d5700e693d18f2649,
                0xd8675a88403abd69a038b9849c5f0d31abade1ee6fd9f8c00422596478d0a3b,
                0x4b538f611b04786661b543e7710ce7733b8cdfda27b177c232eb9dc0248945a8,
            ]},
            {"input": [0, 1, 2],
             "output": [
                0x2e8b9e9db5aa9b30997692e8179e8889f8d889fd5c4edda0757c63ba33143d4e,
                0x15a2d66cc4311b8c66372408a92375be92be6393c3cb645b54e45a527b6a8722,
                0x6a67d661c3944bec4a2e8487a57aa8f36df9b9265c254eed053ac9afa379e3ae,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x3d52bf32e7659fbf115dbe0b9fda87eafbd660a9ab707483549123ec6dd2b363,
            ]},
            {"input": [1, 2],
             "output": [
                0x3a49dd9b66d90c607b0df112c139cfe765d7efcc67031b966a41ba904e46b451,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T4": {
        "permutation": [
            {"input": [0, 0, 0, 0],
             "output": [
                0x18ba523e2f46d4b97e9bb9760665f22652f477f85017d5776d96a8ead68e597e,
                0x573580aec3383a1a75adfe757a46d7e7c6a85a2d617d355acdcfadbcb2dc951b,
                0x44612dffa75fcae8bc8e95e1b420e47b81d33f32b09cd6fbda300253279e2603,
                0x3963e3e06d58ab1456ded5c15dc564f8b933539b73030eccfed9015d982597a4,
            ]},
            {"input": [0, 1, 2, 3],
             "output": [
                0x71d69a22b032b11f2b2bdb34f7dc6025809bb48c30c428627c3c89d5b3eafa62,
                0xf542033826ecc71a488f514c61b54cd348382a482d3f04bbf6c6140510a130e,
                0x11afd216dd0a922dcab1d11dbdc34640eb614054d06b8da10cc55baf7ddbd5a4,
                0x130c1dc37eba717f334491a2aacea584e3e5b5ace38d0276af0f657dc343db87,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x4fd037f8cec88ee947fbceb0b64d154e0bfa31aeff610a62d12124b30bc31029,
            ]},
            {"input": [1, 2, 3],
             "output": [
                0x67505231054b36ab3360006d69627ded4ef7a3bff95506812d7a3fba1cbb796b,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T4_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0],
             "output": [
                0x9f4e16231c7a6e649a1879b1e00250fd61c272328c140753fe9c027f940c6c7,
                0x70b3f6570748b3017c5a7d6439c4bc84e0d33a44de0d825d00c32180fc978af2,
                0x1fd41c635f31ab07e3b0f730675e6c7b0d7216001f84bd4f086474df08d62525,
                0x34804d3e189b31be79f969008b96cf09fe26afb783017745a17ec0728da16283,
            ]},
            {"input": [0, 1, 2, 3],
             "output": [
                0x213abcc0d762c3199072dd66175b8bdc8b59ef8468cfc60ccfc2e1b1df7ed310,
                0x3b6ca99ccc19d6d4874e427a73888d1f47a73463884ad8743a4baf949e388cb,
                0x41ab36b65dec27a6da46c3ca99e73580f6305c32d911ce88e648b968675fdd78,
                0x689bbde3df12b6c0d0256c65f1554052497549fe07966a8214d02f9153e5b26f,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x2810f2c9016cce42a56039c1e8596dbb8b7ccb6083249c64343929f66f138a44,
            ]},
            {"input": [1, 2, 3],
             "output": [
                0x466a3a11032fb20b100ac55da02258c3119d664847b144e037b79f3555aedb5d,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T5": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0],
             "output": [
                0x173147919dd75bc3d43908e7b383bdfbfe5240cd442c880e32150f6bbd7af2fa,
                0x21e3bf71d1e1509614310ec14b1274058f26e2c674447324c69ff301f3a3731c,
                0x1c6de3069dfd52bc07067e7736cae9694780b5620837ec8602b20831fcd59249,
                0x55774ed60f808088b856f31ce24b9022ac0c05bbb6f28a0181872c2fc5e59d19,
                0x1647d69f9d95cbab69be728f474822cce028c66d49eb7de5ffaeeb94788701e5,
            ]},
            {"input": [0, 1, 2, 3, 4],
             "output": [
                0x6833e9becdf81b58a5c8606af65858e9caf3ef7fc4288db7ee3aeeafced3241d,
                0x6df0c8eb6b5ca9841d2c5ed30e622b6573ce8ac4298dd1b171e02fab9f1a14ea,
                0x5dfb958be93cdb85f7f1877c74586f7122cc7e06fd81475a8890bd1c1bab8ab,
                0x495d7199492c6f80dfc9c47314218495eb3bc6c824064c254b90e9d4a8617cc,
                0x1be5f2151baa876dda52d4352a43da437691b11cde69edc3e04a339d9ac33f19,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x19bb5e39c9749e1e3ec24b7393ddf24a6bfdf871b9a584ed4ab0e42eac63ea22,
            ]},
            {"input": [1, 2, 3, 4],
             "output": [
                0x48f78b756a5bc508c35975016136dc12f878b04d4921c90708a554b6cc315a26,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T6": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0],
             "output": [
                0x4a8b15a87e776df65065c139f313a6de377308656b6f47ce4d337626c226afe0,
                0x374486cb91e1f43ee479ab8fc789b085edea1004164700147cc42698803c29f5,
                0x1f9f75f6da62f40c488f6b9ddc902ed9e80d12899d8fba4c441560f99f4fae5,
                0xd138291f26d84682ab4b91305752b193aedb31d2742f8a286afb8d8722a52e5,
                0x527f52e3746689dc07a2a15103701394d4066d8b466b49fa53eb44536aa94ef1,
                0x3aaa08823fe47f8025332c4eb93db239e3f01e69f91b0ed4a0b1b287917534e0,
            ]},
            {"input": [0, 1, 2, 3, 4, 5],
             "output": [
                0x709b4d158370d0a3e2e6cf3fc71fd1ee948f8e9765da4924f0500cdf0022f6e8,
                0x2139583225f724e82ee740a9b48251e959bbd95d617e92a5bb12fbb6cc87bea0,
                0x69c8001e629ef3e105686207cfa8145f3deca862e5e2254d3181cb9a5c2ae703,
                0x2ad5915c415d74cd0433c9220d7b16a0e16ee539d15007400c5597b08bc01f73,
                0x4553e26d1c8cd2330f7f22f59cb48cbc50462a732a88be56f8c78e6d3b2b5e0c,
                0x597a286cc9da26dbbbaf3c0e241249122a7cd14a3d078cf39c3b31ad40787e3e,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x1c467481aea74b5973586677dcc75d140937372af7e49484b9bf60019b913953,
            ]},
            {"input": [1, 2, 3, 4, 5],
             "output": [
                0x4ad0d750c708abb1cfa7344d5fc7088c3920be0745369e6f743ee2c72f7c8eca,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T6_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0],
             "output": [
                0x4de204d01bc1f3105be859e56642d989ca260a2209e7a193056a71efb00c6ccc,
                0x51d78ccc212b95c54ab41a0d1375743261d117dd17e15d4d8cf1a40037b46bbe,
                0x5a803768121ab76827cdc0633f37831b268347756806041875aa93e282007f7,
                0x219323145cac9cac085e2c3c771a2244164e76b4f1937241a04a6d50f53f3411,
                0x1a90f41c835ff5b6c2b9717490d6c5f26e813e6d36594077dd0f2913ebb436bb,
                0x57d6e02fc306f82d3386f05e0f0be0d3a05a70cc6bfa1a5f6c2a544930b40093,
            ]},
            {"input": [0, 1, 2, 3, 4, 5],
             "output": [
                0x298049d50d666d338304002c294ebd61129ffd0c89d58abfc9065cf14c8a0717,
                0x2b0d547b4feb8ee26fe447d2229875e547cea07011cf8081560f099a3bf005fc,
                0x1f5a4e97d3ab673e69b933841ed9d840ea0f5d2e627a30ad74cfc60f12239d60,
                0x1a0c27730824a768f8e9d1cc4e1be86378801a18b92da152827c1036b8733aee,
                0x37d067793f26a8ac945fe993bb51105c44233464074cb47d84b49b06a2045659,
                0x4ca11b7584f19520c2fb7050a214e5f538d10d655d6d27684ba7027bc7350ad4,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x4e1899550c5bfaf42fadca42490a24bfa6037933cd24448f1f60295e771d2cc7,
            ]},
            {"input": [1, 2, 3, 4, 5],
             "output": [
                0x63c1928db540c7e2ff694d1e72ddf5bbb5b4b868d12182ccb66d8f305611f6df,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T7": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x66c7f12781027c04696ea62c3cf516be134682ed4a228ebb0fb2610829dff57a,
                0x6f52b2aa71bf9ceda51634d5e3ce12c5887fff5c8c023cf15a279e9275eefd3c,
                0x15082874b2aafb73fea2c6935235e90eae9faf50e739c770760d3949d7c1e081,
                0x6d0c501d0024adbd3d39af64180e463483c8425a70ad6af148fe9d3ca6d21c70,
                0x54657edae58fecee7ce2cbdd32724e5a27a314ca12504542053d67f05ee1fce1,
                0x8dbd677e6e2d82ef09a3651767d88d98b674b628789976b335d103c014727c5,
                0x1e5b0b2d5cf48cb0a7d1be660db0a402e946d413728da60891b5eaa2dbf6956d,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6],
             "output": [
                0x26b1c226056b6464a7734ee879eaca0d58d36c5c0f2d795b5911d765809aff22,
                0x1b76a0a5084b3c575dc594e7719a9f2e297d1f1bbdd52ee36b33a5f013d18a7b,
                0x3bb0e5c9bb5b0ac3e06fa667bd10cd46a04602814b1819ea42b56eeb5b181b4b,
                0x68a20619ac8c145cb9b04a7748f30ca819443735220f879fbd1ab0cc5dcf48da,
                0x3b57e85bbcf037ef66cdc111fb71ecfbdf95efad5b829e62678437a27351556d,
                0x50ea52e3163b8abea9f5cc5218fa5c49e1bb52c7cab8ed383e0714b54b103565,
                0x664444691f9a50f3bebf181e2a00f707238a0bcac85e1d43c530ed3ce888bd54,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x62c860b2118f9bcb20ca4d3c5108f6613a8e41c559dbe8fff1d8b7bcdbac710a,
            ]},
            {"input": [1, 2, 3, 4, 5, 6],
             "output": [
                0x19727accc574cab4a0993bde49bb22e2d16d16d26e40963d27d1dbb5f55afe05,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T8": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x5fa2e2e9e571ec277fd503bf4e58774ec3c3b4d9ea4d1688e1828f09d46097bb,
                0x64cf68646588947a4eeff6c626ac892bd7aaa0bd12f763bc9f450a41c464fab6,
                0x25e4400208788c3bd0086a2fca2cbdb910e48ce10c64d8977358d6833bf8c4bf,
                0x4f07e2361110d38cc00918f9303a2fa2e6ce43f39e5046eb7e4d2817bb9d26e4,
                0x47900ebd0b766c7a16e6c7ee94349b16ced10f0ab2951773b0f019533d9344f9,
                0x333e9fe1f65d6e964386626f525cfa219af27384ab172dad14a03eb5f654b399,
                0x1b105831b6cb5a51b19f558f89baba333b5d674e7aadaceb0f6ae02b2fd3d90d,
                0x4b0626d77e9f65e678397804fc02261bc25962e577c8eb4c2c782b6bf119633,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x411fbac5425d3610db13bbcfdb44ae28cd43a35dd7cf7663146eac63c463d8a2,
                0x4178616cbab9a9a375054d54edafaf4e6031dcc1539f3148596eadcb293e1d80,
                0x6a1388cf3575e7555965caa4adc5532f0236a813ac967cb2fb7470b0fed84481,
                0x3a1e9353f89c16e27afe4012e2f7788c63979c4398792e9ce2326f0f98a47ffa,
                0x1f14093f7da2968b3e4b344d64db152fd61238f5661db0346f308252bc9012e5,
                0x6ae1d4d8882ba96c097b07c10f714f9a807e54f39ba372d6c825af9a4ca09aaf,
                0x8aaac46feeac295e645c677d6cc51733488aff78ba5b976146b8f1720d989ad,
                0x6151a8d9bfcb9ca63838d0b0ed53b88b3be3ba96dcdc59ccaae3d7bddd32c065,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x42e4901e01eb54662996ccce925b5c37e8c2d9eef5ad06d273e974af4c8e5c73,
            ]},
            {"input": [1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x18301254925eeef579efa045e6cc2cfd41f4dd98abf6a2e7d7cb0d9655ef4655,
            ]},
        ],
    },
    "BLS12_381_SCALAR_T8_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x2d34d0bdeba40805dff0fc3bfd9e4c7efb63030b3c2003016736eb60c3d87c92,
                0x3c0e42ec5be79cc64ea107db1daa419b6e15f014a56c7f23de82c5f7a9c168cd,
                0x483f87c8336f50c33ac1f7f94d3e6c0ecf806d7ed46d8c46e4761388457c37a0,
                0x283fce25919c2eb80a45fe86c3042bcd2fe931e39da82d2e2ce782feb68bdfaa,
                0x20ce6d2b2501bd8fc60183d8b9da8b142984466a3c4b764fc858ee1f49a54cde,
                0x38f7e824576150d44513d639d33f8f481e9f074a75833fafce6be5bbe58b60cc,
                0x96b60d5a0fd0d05857d33def780adffe87294c7e996eef25201a1d8382a6a54,
                0x20893cfd5f755d700c09a9e87a6f621e7a32f55bf230adce1eaf59234982e054,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x11889df0e6cf4c66acfb469f7d59fe9480d09b6398afcf398b8130b99d452853,
                0x4a50c86c0e7ef0412565af9cb800f262844867f006836dc7980c770310b05891,
                0x546e4f2ff7c5d8252a7de4493f97537304f673d36615e58b7474f0c2ac077c03,
                0x77e39cacba7cfa99e89da112361b7eab0a550d09c5a9fb2b1426094d03f1f8f,
                0x72e1a9dc031effd8d9cc7165e722b7b15c891f20de37c6e89dc153fd9beb0d06,
                0x21cdc377daf91bd9a11371c214309b3f7cb070fe19947548911f4d31f51ad566,
                0x6ddbedf2561a69cf5403598a5f0c8ea3f930e5c264e6f3d72f14f1ff57cf51cf,
                0x6d4bce43e78f7d8ffc8b443574ec7a70ae248ad1688e415b2d4ed5091a0f27a,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x41cd5702c2a2d73aed7a365ea000f0b39d536c2dce9dfa9f7cb83bd2f59d42ef,
            ]},
            {"input": [1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x3c443e25ebb967dfd464f4902b4de297c60d62e6e58afc602e47ad37271cde9a,
            ]},
        ],
    },
    "BN254_SCALAR_T3": {
        "permutation": [
            {"input": [0, 0, 0],
             "output": [
                0x484f2d1cc8dcc1fbd9cb5939a176b678769fce074ce1f5973ca60009717b2ad,
                0x244fd37b91fd9570e4357658903b3b55ab7dd22be8181f5ae878679cba837099,
                0x1938bf117dd42fd83aa2d68b16a95326bb4a46faad1f7cc4f2f53fe08ac982e4,
            ]},
            {"input": [0, 1, 2],
             "output": [
                0x118d563b447bfd0b5e378c854df4c777381208af4d3c552bfc24de1c6464ef60,
                0xd53ba836ecf6ebd13d6f49aef1fbfb37a6b875e43f5ef48b2ef04667e025a7b,
                0x2b2f3d37cfc97b690ee00393b227963f5d39eda8044611e39d0f0f315f66a13e,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x34dd494bd7d8de367c67b52cb06a69c01e28cf72222b7c163510d834e40254c,
            ]},
            {"input": [1, 2],
             "output": [
                0x7b67c154e9e172ac2dbcc54c5636afc1f96691a5e3eaa86531ec7c4de85d04c,
            ]},
        ],
    },
    "BN254_SCALAR_T3_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0],
             "output": [
                0x13c4f9f260fa8bfc4624f853dcfb96788fe9a7b5d4ffa6dab81eb074dcf77fa2,
                0x23c635dffd30e6d91c8cd9c22eb81f03a57e1eea9d99935fe38c4268b331c613,
                0x18cbc450dff8e5e4c2b36c9b32bf24b996107d1971a0e71f15815897490bd542,
            ]},
            {"input": [0, 1, 2],
             "output": [
                0x18481596a77f529a509b9c48630e33eadfc9352839b6f4b3f65ef05e69a84329,
                0xa27dc61b5cc3198b1f8dec06d078caaf328430ac0c74d521d264ce7ee5160d6,
                0x2d4f66c6e899277ac962f5abc7aa8cb72970aa004b7ebe73876dabf1c07d3535,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x2f84bb723b6ad94335cf60b69aaa06efc6ce59085242af30fe8ca82ded679130,
            ]},
            {"input": [1, 2],
             "output": [
                0x379b7876c34bbcf4494e18d63902ad774407d5fe8718bc2f84a6183964d268a,
            ]},
        ],
    },
    "BN254_SCALAR_T4": {
        "permutation": [
            {"input": [0, 0, 0, 0],
             "output": [
                0xc9f74f5180237f8702ffad87a8cd81a9c1af0c83a7e2b08f25609e4a1a30e02,
                0x252001efe8dfd24225e05ec64ca700678c1e4990ac56bf759d92ebf654b31e02,
                0x20812c511c1f59e659fafcb2f330b620c9e91e3de40e4d968a3c906c47c66edd,
                0x1875921b3f11df1425291b3731cac4bf37b9601e0f7acafa89dd91768bfe0d9,
            ]},
            {"input": [0, 1, 2, 3],
             "output": [
                0x2c8ca718fc19736404350c5cfe0c56a38c582cf20bac67db8b7ec77640e4a74e,
                0xa0c332f22888e2a56d6c1626dad6d9d7d792c319b74e962aa48abbd4c32b27e,
                0x2ef6510d85b2cc3e0a455a128f331462e0f189e2b8966280553266e6cc2c54be,
                0x1e5e1e3fde2e4ad435c91e04965b7f03ed56d2aabb33e6b8e0b3180de820a229,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x19091b7e190b5fbff681d093e5d2c446af86cdb63b7ff332708672d25da3557d,
            ]},
            {"input": [1, 2, 3],
             "output": [
                0x25be0a89c72b9f2b4b30265ed48fdc4087ef17e1433903d93afe05863a3a9868,
            ]},
        ],
    },
    "BN254_SCALAR_T4_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0],
             "output": [
                0xa1687663cbc8c17e3cab83ab2abdc6e48675392534f41ca3f2943c68a97a995,
                0x16f61bfef1a3d80a31162ea4b99b8fce0db8368895ae6d16e4bd82bb0d63b243,
                0x25280ae9cb472b448ea57be6488d4677306d1757c349c96efe4c16146193eb1b,
                0x2db40b47ebb0658ece1a197a5d1c602f263cf6d84cde49e026c6dd6a7e03fb42,
            ]},
            {"input": [0, 1, 2, 3],
             "output": [
                0x23e5cc9b9521406cbb03246e1377e0cc77e5fbb2aa39d54d09d0ead297083cf2,
                0x104b0642e45d9d06279efc10f397d3ce075440a2179d5f44a04efc0ef3d67736,
                0x3e9f6060f145dc1ed1c9cb0d4d27a89e16af9961914a2e4c12fb601018404e1,
                0x2d9662ed9e88b7006c300c3a43a52dd16bc243482e40467933ce629ebddc0f0b,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x2e5c456b6805cb8599e1dbc65a981e343084ecd8dba381db3334478eb74bfccd,
            ]},
            {"input": [1, 2, 3],
             "output": [
                0x2ddf0ba169445bbbda6a65a382b54c5667519bc74a81598ea281977e7b203dfc,
            ]},
        ],
    },
    "BN254_SCALAR_T5": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0],
             "output": [
                0x434a5c1225855b7eea8a964f9ec793e0d07fa340d44a35b40dd1a1dddaba403,
                0xa93b8f52e32fcea76ddba241b2b280786e5780b12a87bac3396bccd79b77e07,
                0x277f85eef64949bc6961308eb57017ecf2afe3c80a825284c354938c8ade44a2,
                0x1cfa04304a3c7270c729585a723f1be4a3f76cb6bb16552f6c93271ed9dd06c1,
                0x14531fd460f76bd8c6a2dea8c1508f1785c8e5c592bda19a467a108bf4a123e8,
            ]},
            {"input": [0, 1, 2, 3, 4],
             "output": [
                0x5a7597da08d4a8cedd3e393920ac0dc668eafa616ac316ad2fa46b5d3bfeae5,
                0x78f73f36daef76008a7cb64c6f2a2bb2e6c66e98f2aabd13b7cf9e2cec6e7f6,
                0x199cf800b201aaeb07af9e93e41adc486f4ea27771777203aedf642b5d92197b,
                0x107f6e8ac95778d630b1ecfde1ba077a50d2d5f274e68ca47a6952c7710258bc,
                0x18eeab95633d41e4b97cf0b462ed383d473599ca680f49c8c8690b88d653f10d,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x25f406a1afaeed25c0a45d76eea2729b2b895416ad706e80c8f24dbda1eae8e4,
            ]},
            {"input": [1, 2, 3, 4],
             "output": [
                0x22d157535c4a89ea6b532f63b83124d2cff072207456f3d36e633b8b793763a1,
            ]},
        ],
    },
    "BN254_SCALAR_T6": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0],
             "output": [
                0x29d194491c1a6336d4e8b2a52ea87fbabc53ea22561382f852825921df9c3bf7,
                0x23494691a0e88548f1b496ed03bf34222156147299346da5ea4d2a82419d50eb,
                0x1377c806965576bd0e92088e5ff35d3bbdd5a05d126fc2bc33ccccdc059dc892,
                0x223bbfb7350007f63361b5221e3b4d23939adf39a01f13aa97d0617f293e3492,
                0x278443583af7fac411f2d608adecad307ce535bcf1537c5ae858cc3d936191f0,
                0x5d2663ad5f72743ef4b5f7c3d828059c88051880d0746fbdcdbc3daac59b301,
            ]},
            {"input": [0, 1, 2, 3, 4, 5],
             "output": [
                0x451bbe4cadb71d5bf71e84819e3422ed9055f5644633490fb2042658bd6b9a8,
                0xf12c3b614deeaac65321d4622190b7366619538bbd46cbac76deb82a4f31ae2,
                0xa8ebf4f78605596bd2520a81b77034214c768f3b666f534937c59a392927f0,
                0x1467cb8842d9509e19f85b6def52cea82cff1fb5aa1d74ba91c49a2e520506c1,
                0xdf294af03c27d7982d875a59446fa19ceb69be48234560794850e91b607a685,
                0x76519b384696601e6d877f1c2f32a39c21966fdb2dd4d4af3d7f75d21ceb1e5,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x2211be2e5fa6b700bf2a950ccd5389077f9403b91a10b7d9c18d3eb8636f9008,
            ]},
            {"input": [1, 2, 3, 4, 5],
             "output": [
                0x1d9e1e0a7246a0592925f0808b4a1fd5402967efb3a88aa82be698896e3f8914,
            ]},
        ],
    },
    "BN254_SCALAR_T6_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0],
             "output": [
                0x2d893d27dc11792af514745fad261900e5defedeead390f1c6e4cd58960064a7,
                0xb574959dc6b381e54b63c25261501ca55846ccdcdfb486bf5bb27555eec221d,
                0x23ad609be2f455b0e351803742acdecfe2457c0b35153ce5d88b8b8b59557c24,
                0x2534cba84032bf57306ca2f3d82c659ea51a84dcd1dde9709e0c381363abe7b1,
                0x438c7141d3aef4673dcd12265c3edced64b1c404c75bfb29d091757cd7a3cdc,
                0x99b9d29d86a5af50fbae285870bec7b6ce05cd77663d565f3548a31975940e1,
            ]},
            {"input": [0, 1, 2, 3, 4, 5],
             "output": [
                0x2963747030dd7fb8791d1a725591be10db51c498aa51078aef2c9d84c5ea13d1,
                0x927cc0b042203fcae58eab1ca99b525188898c37279f503a5ea27ed17d9c19c,
                0x12904ad43ae23e3db5b95bb165e45a38adc90649cf195abc2773bb05f92a8994,
                0x2ac48e9e2d09df800d541f49e42e6f0bc43eda996b22ea198fb14fa7f35cdd31,
                0x17894f0cc8ba882571fbbd091d0b8756f7d25c41b773be70dae5f99986109c2f,
                0x1a5e81ff8035c0e10c7698113b580ac35d0f149f958353c81bda10a1afccb3fc,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x1c246e35e51359d89ff00be86bafd76dc49390831939c346ae637da196dee062,
            ]},
            {"input": [1, 2, 3, 4, 5],
             "output": [
                0x8d987fb729443706b7e9874ef2fcac34c935033e7fd29a9fdc3becda52ab02d,
            ]},
        ],
    },
    "BN254_SCALAR_T7": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x2e50c41e15292ab4c7637c30ff38ddefd8647970acb39af36f45060a1bf8d08b,
                0x28b28250a9cd470cf696fb6f6b7e660de0ca1aa7cfe8e4d74b57f7109113859c,
                0x2f82005f5db955cd74939cc966fd90efee032e726f75da73ce2baa8d9dbec28c,
                0xce968bc3cc7648ebfbdd7ab96fafa50c61ca782dc0c22b7b7a07c74cf973a4c,
                0x3465aeacacd0452f795d9d5b7ebcd785efc6fce2c0bb9a03b686496459383c5,
                0x1081b8d360532721238dd7b7540161d3f53aa6d5202c47fe3a20b8ba63101630,
                0xaabd237bd6d893e1015186c21ff5957b07ce7dc54d9d0a645a5fe4dc2872cca,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6],
             "output": [
                0x20843ec1667a4fa8e4279b9c8f476bb2a266b3a53dc95126f3f61518da5962f1,
                0x16cc69bb5d76a99a6c0b25a6904f3d34a1fa514e615f8ced181620774e6e353b,
                0x13eb7a613bfa3af119d8596dc5ad35891cef52302404d7421a04dc1751923bda,
                0x2450bef988a11d0d10a277a2e9c79eee1d96abf8ba31f7b96ccd380652473526,
                0x22be84dd84ac7042cef21d085ebdc606533a2fbdb3965ee0a457a23a6b1a6832,
                0x2b6c6b6dc1cb5609b32e88339cb8a3681f7aa93b458f1a208112769736144bc8,
                0x11e0b80df2235462a7312752ac605a98ea3b0ba7312b867625fe2d841b9d775e,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x2e430f4d48f72b798b9d39036baf4ca226335cb26cf260a890e186cbcefb2694,
            ]},
            {"input": [1, 2, 3, 4, 5, 6],
             "output": [
                0x38828b95d2111203424938dc49eecc6e00dc8c0a659e50f489daa89e56476cd,
            ]},
        ],
    },
    "BN254_SCALAR_T8": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x1b3786d1cc6e17dbcdb94e550dd6f8a9508e4ccf1e84414fd2c9c68aec7fe41f,
                0x13a340ead10999fff50641dc9cf5a088532ed111d4defd5a21bc05188ea7557e,
                0x10d0bcf5ccc4ecefedc24bee1bf0de21261d38f67f7bbd78266ed0054ee001b7,
                0xc42b524ef19dbf67b02388fc7b856b12b68558899339bb6f81d0cc82f34d3b6,
                0x2f9386aca14e8ce836f44c42698d5f8fa2dbb66a12672706dae571ec8f01ff70,
                0x22bac6a4cea515dcfa39f075871f5fd1a77d863cedfb21f61d50e0bd47127e11,
                0xb1e529b99a78b644860cce677dd0a2f33013de13d9005fb59077454d0354a30,
                0x1ed8ed548290ba7733f561d3d3c7ecf2e7783c040d5f3044550116f49241d8a9,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x12e8cdc1ea0d8835b066a96e06482edcb1308a94fea5c58862eb77815fe93df,
                0x1564282dc7b81fe65075d0e3da47cbc5eb6b1c62ba1321580033ccb44fdd88a8,
                0xb4cad534602f0bee92588e98333eff13f699f71401ecffe4e767994ce8e9d8c,
                0x243ba0cefbbd6d780dde6b36ef759205e0d7b0448447e6c271ffbc3efeea8128,
                0x2aca66770c54fc04194ed82d33893ed87072805ba5625c74a99cfef62b9c6198,
                0x185527e0262bec6ba7a432afbc11ce426053f6416819a15fd7aa6b31b5be2533,
                0x1fe4373b1aa1c5f4a049e67432d07b1e412bbe1ac6630968e5b84c5cb54e59d,
                0x11eb44c56893d8bfdbadf78a90dd2177a12280aba326f52f85328e64389d33e,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x6bc174d311402fd97320f58d04e5624b4fa8b042172b36c0b7aff9f6a919582,
            ]},
            {"input": [1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x2f759fcb74f21aea3bcfded0c814c1d892e5bfa628a5fa50d927ea7ab3638460,
            ]},
        ],
    },
    "BN254_SCALAR_T8_TIGHT": {
        "permutation": [
            {"input": [0, 0, 0, 0, 0, 0, 0, 0],
             "output": [
                0x338c57407726cf4fb775f8db8fec4e841199dd888df37ba025c2be38ee092e6,
                0x1d60d503a44f6dc0e721c94e18f0f12f2b973f4a5386e4f1fbcbbdc1f551929a,
                0x1b7526f7a4ad03c5ab40fa7970d5bfa2ee252b58b10576de28994248919542a4,
                0x292fd153d4b325c0fce1edd477a15d5446bc77d848f12fdd7ad474230739397b,
                0x71aae0b4e598e028b0bc9c09c55663a5dd6656000540a7f59cc68ad5223364b,
                0x1b753996a23ec19da4349b1a145bc3354af1d0f75a0a7e138629c411961f1a29,
                0x1aa1d69a3bae6d5f362960ad2fcb822dee020fca73fac669cdfd94c7f3fa76be,
                0x1816d7bb85733d17cf6f255035e33fdb7e70551e4e5432e6e1f2dd5197673dcc,
            ]},
            {"input": [0, 1, 2, 3, 4, 5, 6, 7],
             "output": [
                0xe89aa431fa25e9de004e4b2df8f9d0cb3714e1706834b024a808d45f05bdf2c,
                0x1f5d65119bd6dcf6e9409115c76bf98c73372d91220264548417309f473ee060,
                0x1174cef6b4524609a8a8d24ad6fba1b7bce25abdae294b075c9c2111b595c0df,
                0x9b740aaaa70cbc6477f69fcb502e855d4a0060ff9729e6f47d77e6ab36dd071,
                0x27324a98213dacba12e85e4aa67f813d0dd16fe0b9332d0e05934cb5b37459ab,
                0x10f7ded03379cec325193b6cd42f32bef9596901cd669f8277b12779291e71bf,
                0x261af69cc9f2881db588f8044396bb0a10808c91eef33945ee5a88961fe160a7,
                0x2b0f73b3431ab1e86f8afa8ca251725cf0eb6708fd28a267db59b70ff845df42,
            ]},
        ],
        "sponge": [
            {"input": [1],
             "output": [
                0x1a85adb7f62aa0f3600a7c910eda64ff5e6111c98640d95944d5870ecbccb6a3,
            ]},
            {"input": [1, 2, 3, 4, 5, 6, 7],
             "output": [
                0x10fc849997b7d55f8893aef15d54d99f961aaccffe636b6092fb596fb2999d2f,
            ]},
        ],
    },
}


def _reference_input(label: str, t: int) -> list[int]:
    """The fixed inputs the reference vectors were generated on, by label."""
    if label == "counting":
        return list(range(t))
    if label == "zeros":
        return [0] * t
    if label == "negative":
        return [-(i + 1) for i in range(t)]
    raise ValueError(label)


# ---------------------------------------------------------------------------
# 4.1 Known-answer tests
# ---------------------------------------------------------------------------

def test_permutation_kat_reference():
    # T4_TIGHT is the single shipped reference instance whose parameters match the
    # paper, so its vectors apply to our named instance directly. The other seven
    # are covered by test_permutation_kat_reference_reconstruction below.
    prim = Polocolo(POLOCOLO_BLS12_381_SCALAR_T4_TIGHT)
    for label, expected in REFERENCE_PERMUTATION_OUTPUTS["T4_TIGHT"].items():
        inp = [prim.to_field(x) for x in _reference_input(label, prim.t)]
        assert [prim.from_field(x) for x in prim.permutation(inp)] == expected, label


@pytest.mark.parametrize("ref", REFERENCE_INSTANCES, ids=[r[0] for r in REFERENCE_INSTANCES])
def test_permutation_kat_reference_reconstruction(ref):
    # Reconstruct each shipped reference instance -- including the ones deviating
    # from the paper -- via explicit parameter overrides and check it against the
    # vectors generated from the Rust code. This pins the whole engine (S-box,
    # linear layer, round structure, constant generation) for t in {3, 4, 6, 8}
    # and m in {32, 128, 512, 1024} against the reference implementation.
    name, t, m, R, M, m_rcons = ref
    rcons = None
    if m_rcons is not None:
        # chimera: the reference generated these round constants with a different
        # m in the seed than the m used by its S-box
        seed = f"Polocolo-{m_rcons}-{R}-{t}-BLS12".encode()
        sampler = XOFFieldElementSampler(seed=seed, p=P_BLS12, xof="shake_128",
                                         sampling="bitshift", endianess="big")
        rcons = sampler.grid(R, t)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ParamRecommendationWarning)
        params = PolocoloParams(p=P_BLS12, t=t, m=m, R=R, M=M, rcons=rcons, r=t - 1, c=1, d=1)
    prim = Polocolo(params)
    for label, expected in REFERENCE_PERMUTATION_OUTPUTS[name].items():
        inp = [prim.to_field(x) for x in _reference_input(label, prim.t)]
        assert [prim.from_field(x) for x in prim.permutation(inp)] == expected, label


PERMUTATION_KAT_CASES = [(name, params, kat) for name, params in INSTANCES
                         for kat in SELF_KATS[name]["permutation"]]
PERMUTATION_KAT_IDS = [f"{name}-{i}" for name, _ in INSTANCES
                       for i, _ in enumerate(SELF_KATS[name]["permutation"])]


@pytest.mark.parametrize("name,params,kat", PERMUTATION_KAT_CASES, ids=PERMUTATION_KAT_IDS)
def test_permutation_kat_self(name, params, kat):
    prim = Polocolo(params)
    out = prim.permutation([prim.to_field(x) for x in kat["input"]])
    assert [prim.from_field(x) for x in out] == kat["output"]


SPONGE_KAT_CASES = [(name, params, kat) for name, params in INSTANCES
                    for kat in SELF_KATS[name]["sponge"]]
SPONGE_KAT_IDS = [f"{name}-{i}" for name, _ in INSTANCES
                  for i, _ in enumerate(SELF_KATS[name]["sponge"])]


@pytest.mark.parametrize("name,params,kat", SPONGE_KAT_CASES, ids=SPONGE_KAT_IDS)
def test_sponge_kat_self(name, params, kat):
    # cases cover a short (padded) input and one exactly rate-sized block
    prim = Polocolo(params)
    out = prim.hash_sponge([prim.to_field(x) for x in kat["input"]])
    assert [prim.from_field(x) for x in out] == kat["output"]


# ---------------------------------------------------------------------------
# 4.2 Roundtrip (invertibility)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_roundtrip(name, params):
    prim = Polocolo(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation_inv(prim.permutation(inp)) == inp


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_layer_roundtrip(name, params):
    prim = Polocolo(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    for r in range(prim.R):
        assert prim.linear_layer_inv(prim.linear_layer(inp, r), r) == inp
        assert prim.constant_addition_inv(prim.constant_addition(inp, r), r) == inp
        assert prim.nonlinear_layer_inv(prim.nonlinear_layer(inp, r), r) == inp
    assert prim._pre_rounds_inv(prim._pre_rounds(inp)) == inp
    assert prim._post_rounds_inv(prim._post_rounds(inp)) == inp


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_sbox_roundtrip_and_zero(name, params):
    prim = Polocolo(params)
    for x in [prim.F.zero(), prim.F.one(), prim.to_field(-1), prim.F.random_element()]:
        assert prim._sbox_inv(prim._sbox(x)) == x
    assert prim._sbox(prim.F.zero()) == prim.F.zero()   # S(0) = 0 by specification


# ---------------------------------------------------------------------------
# 4.3 Consistency
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_deterministic(name, params):
    prim = Polocolo(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation(inp) == prim.permutation(inp)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_distinct_inputs(name, params):
    prim = Polocolo(params)
    inp1 = [prim.F.random_element() for _ in range(prim.t)]
    inp2 = [prim.F.random_element() for _ in range(prim.t)]
    while inp1 == inp2:
        inp2 = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation(inp1) != prim.permutation(inp2)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_output_sizes(name, params):
    prim = Polocolo(params)
    assert len(prim.permutation([prim.F.zero()] * prim.t)) == prim.t
    assert len(prim.hash_sponge([prim.F.random_element() for _ in range(prim.sponge.r)])) == prim.sponge.d


# ---------------------------------------------------------------------------
# 4.4 Derivation and constants
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_m_and_R_derivation_reproduce_tables(name, params):
    # The instances spell out the m of Table 1 / Table 7 and the round numbers;
    # the derivation helpers must agree (i.e. omitting m and R would build the
    # exact same instance).
    assert params._init_m() == params.m
    assert params._init_rounds() == params.R


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_m_derivation_strategy_reproduces_tables(name, params):
    # _init_m short-circuits through the RECOMMENDED_M / TIGHT_M tables for the
    # official state sizes; this exercises the underlying selection strategy
    # (_derive_m: joint (min R, then min m) over the powers of two dividing p-1,
    # capped at 2^M_MAX_LOG) and checks that it reproduces the tables from the
    # round-number bounds alone -- for every official instance, both fields,
    # recommended and tight.
    assert params._derive_m() == params.m


# Table 5 of the paper: log2 complexity of the guessing power residue attack
# (Guess + Determine columns) for the recommended and the tight parameters.
TABLE5 = {
    (3, 6, 1024): 170.49, (4, 5, 512): 164.59, (5, 5, 128): 162.19,
    (6, 5, 64): 167.47, (7, 5, 32): 164.53, (8, 5, 32): 185.43,
    (3, 5, 1024): 138.42, (4, 4, 1024): 137.95, (6, 4, 64): 128.27, (8, 4, 32): 141.84,
}


@pytest.mark.parametrize("t,R,m", TABLE5, ids=[f"t{t}-R{R}-m{m}" for t, R, m in TABLE5])
def test_guessing_power_residue_complexity_reproduces_table5(t, R, m):
    total = t * (R - 1) * log2(m) + uni_solve_comp(t ** (R - 1), P_BLS12)
    # the paper prints two truncated decimals; the exact values deviate by < 0.012
    assert abs(total - TABLE5[(t, R, m)]) < 0.02


SIGMA_CASES = [(field, m) for field in (BLS12_381_SCALAR, BN254_SCALAR)
               for m in (32, 64, 128, 512, 1024)]


@pytest.mark.parametrize("field,m", SIGMA_CASES, ids=[f"{f.name}-m{m}" for f, m in SIGMA_CASES])
def test_sigma_interpolation_conditions(field, m):
    # sigma must satisfy the two interpolation constraints of Section 4.2 on every
    # field it is used with (the derivation seed does not involve the field, so
    # this is a genuine per-field property).
    sigma = power_residue_sigma(m=m, p=field.p, g=field.generator, method="shuffle")
    assert sorted(sigma) == list(range(m))
    assert sigma_conditions_hold(field.p, field.generator, m, sigma)


# The straight-line constraint programs of Appendix A.1 (one addition gate per
# assignment). Evaluating them on unit vectors must reproduce the pinned MDS
# matrices -- this guards the transcription of both the matrices and the programs.
# Matrices were pinned since the randomized search of Appendix A.2 
# (utils.matrix.low_addition_mds_matrix) was not seeded.
#
# NOTE two typos in the constants of the reference implementation (plain/
# polocolo_lins.rs), which the appendix constraint programs arbitrate against:
#   * its MDS3 has row 2 = (1, 2, 2) instead of (1, 2, 1) -- that matrix is not
#     even MDS (the minor of rows 1,2 / columns 2,3 vanishes);
#   * its MDS6 has 4277 at position (2, 0) instead of 4227 -- inconsistent with
#     the reference's own row 4, which equals 3*row2 + 5*(2*w9 + 6*w5) only for 4227.
CONSTRAINT_PROGRAMS = {
    3: ("w1=x1+x2; w2=w1+x3; w3=w2+x1; w4=w2+x2; w5=w2+x3",
        "w3,w4,w5"),
    4: ("w1=x1+x2; w2=x3+x4; w3=2*x2+w2; w4=2*x4+w1; w5=4*w2+w4; w6=4*w1+w3; w7=w4+w6; w8=w3+w5",
        "w7,w6,w8,w5"),
    5: ("w1=6*x1+x2; w2=2*x3+4*x4; w3=3*x1+8*x5; w4=8*w1+3*w2; w5=5*w2+w3; w6=4*x3+5*w5; "
        "w7=8*x4+6*w1; w8=2*w1+2*x5; w9=w7+w5; w10=2*w4+2*w9; w11=w8+7*w4; w12=w6+2*w8; "
        "w13=3*w5+5*w12",
        "w9,w10,w11,w12,w13"),
    6: ("w1=4*x1+7*x2; w2=2*x3+2*x4; w3=x5+5*x6; w4=3*x1+4*w3; w5=5*w1+4*x5; w6=5*w2+5*x6; "
        "w7=3*w1+3*x3; w8=8*w4+3*w2; w9=8*w3+7*x4; w10=2*w9+6*w5; w11=w4+7*w10; w12=7*w8+w11; "
        "w13=2*w5+8*w8; w14=5*w11+w7; w15=8*w11+6*w6; w16=3*w14+5*w10; w17=5*w9+4*w7",
        "w12,w13,w14,w15,w16,w17"),
    7: ("w1=5*x1+5*x2; w2=8*x3+5*x4; w3=3*x5+2*x6; w4=8*x1+6*x7; w5=6*x5+6*w1; w6=2*w2+2*w5; "
        "w7=8*w6+7*w1; w8=7*w5+7*x4; w9=7*w4+6*w3; w10=x6+w4; w11=8*w8+3*x7; w12=8*w11+4*w2; "
        "w13=8*x3+7*w12; w14=8*w12+6*x2; w15=w12+2*w1; w16=8*w3+5*w15; w17=6*w16+8*w14; "
        "w18=8*w9+6*w7; w19=7*w16+2*w9; w20=8*w17+7*w7; w21=5*w11+3*w17; w22=w13+5*w10; "
        "w23=w22+w17; w24=4*w16+6*w8",
        "w18,w19,w20,w21,w22,w23,w24"),
    8: ("w1=3*x1+5*x2; w2=4*x3+3*x4; w3=8*x5+3*x6; w4=5*x7+4*x8; w5=4*x6+7*w4; w6=5*w2+w1; "
        "w7=3*w3+2*w4; w8=2*x1+6*w3; w9=4*x3+6*w7; w10=8*w5+x2; w11=3*x4+2*w8; w12=6*w9+6*x7; "
        "w13=5*w1+5*w12; w14=4*w13+2*w5; w15=x7+6*w13; w16=8*w11+4*w5; w17=6*w16+2*w6; "
        "w18=2*w10+5*x6; w19=5*w16+8*w12; w20=2*w19+w18; w21=3*w2+8*x7; w22=w10+4*w13; "
        "w23=6*w20+4*w21; w24=2*w23+w12; w25=4*w18+7*w17; w26=7*w22+3*w23; w27=6*w16+4*w14; "
        "w28=7*w25+7*w14; w29=w20+7*w15; w30=2*w8+8*w20; w31=4*w19+7*w6",
        "w24,w25,w26,w27,w28,w29,w30,w31"),
}


def _eval_constraint_program(t: int, program: str, outputs: str) -> list[list[int]]:
    """Evaluate a straight-line program on the unit vectors, i.e. extract the matrix
    each output variable computes."""
    env = {f"x{i + 1}": [int(i == j) for j in range(t)] for i in range(t)}
    for stmt in program.split(";"):
        lhs, rhs = stmt.split("=")
        vec = [0] * t
        for term in rhs.split("+"):
            coeff, _, var = term.strip().rpartition("*")
            coeff = int(coeff) if coeff else 1
            vec = [a + coeff * b for a, b in zip(vec, env[var.strip()])]
        env[lhs.strip()] = vec
    return [env[o.strip()] for o in outputs.split(",")]


@pytest.mark.parametrize("t", sorted(CONSTRAINT_PROGRAMS), ids=[f"t{t}" for t in CONSTRAINT_PROGRAMS])
def test_mds_matrices_match_appendix_constraint_programs(t):
    program, outputs = CONSTRAINT_PROGRAMS[t]
    assert _eval_constraint_program(t, program, outputs) == MDS[t]


@pytest.mark.parametrize("t", sorted(MDS), ids=[f"t{t}" for t in MDS])
def test_mds_property_over_official_fields(t):
    # Checking the minors directly over GF(p) takes minutes for t = 7, 8 (12869
    # 255-bit determinants), so check them over ZZ instead: by Hadamard's bound
    # every minor of every order is at most the product of the row norms (each
    # factor >= 1, so this also bounds all submatrix minors), which stays far
    # below both official primes -- hence a nonzero integer minor is nonzero
    # mod p, and MDS over ZZ implies MDS over both fields.
    from math import isqrt
    minor_bound = 1
    for row in MDS[t]:
        minor_bound *= isqrt(sum(x * x for x in row)) + 1
    assert minor_bound < min(BLS12_381_SCALAR.p, BN254_SCALAR.p)
    assert is_mds(MDS[t])   # integer entries, no field: minors over ZZ


def test_m3_m4_are_the_duval_leurent_matrices():
    assert MDS[3] == circulant([2, 1, 1]) == [[2, 1, 1], [1, 2, 1], [1, 1, 2]]
    assert MDS[4] == dl_m44_84_matrix(2) == [[5, 7, 1, 3], [4, 6, 1, 1], [1, 3, 5, 7], [1, 1, 4, 6]]


@pytest.mark.parametrize("m", sorted(REFERENCE_LUT_SAMPLES), ids=[f"m{m}" for m in REFERENCE_LUT_SAMPLES])
def test_lut_derivation_reproduces_reference_samples(m):
    # The derived sigma/table must reproduce the tables shipped with the reference
    # implementation (sampled entries; the full tables are pinned transitively by
    # the reference permutation vectors above).
    sigma = power_residue_sigma(m=m, p=P_BLS12, g=BLS12_381_SCALAR.generator, method="shuffle")
    lut = power_residue_lut(P_BLS12, BLS12_381_SCALAR.generator, m, sigma)
    assert len(lut) == m + 1 and lut[0] == 0
    for key, value in REFERENCE_LUT_SAMPLES[m]:
        assert lut[key] == value


@pytest.mark.parametrize("seed_params", sorted(REFERENCE_RC_ROW0),
                         ids=[f"m{m}-R{R}-t{t}" for m, R, t in sorted(REFERENCE_RC_ROW0)])
def test_rcons_derivation_reproduces_reference(seed_params):
    m, R, t = seed_params
    seed = f"Polocolo-{m}-{R}-{t}-BLS12".encode()
    sampler = XOFFieldElementSampler(seed=seed, p=P_BLS12, xof="shake_128",
                                     sampling="bitshift", endianess="big")
    assert sampler.grid(1, t)[0] == REFERENCE_RC_ROW0[seed_params]


def test_sigma_hashtape_variant():
    # The published param_gen.sage derivation must yield a valid (condition-passing)
    # permutation -- a different one than the shuffle variant the shipped tables use.
    shuffled = power_residue_sigma(m=32, p=P_BLS12, g=BLS12_381_SCALAR.generator, method="shuffle")
    tape = power_residue_sigma(m=32, p=P_BLS12, g=BLS12_381_SCALAR.generator, method="hashtape")
    assert sorted(tape) == list(range(32))
    assert tape != shuffled
    assert sigma_conditions_hold(P_BLS12, BLS12_381_SCALAR.generator, 32, tape)


# ---------------------------------------------------------------------------
# 4.4 (cont.) Toy instance and the MDS search strategy
# ---------------------------------------------------------------------------

def _toy_params():
    # p = 113: 112 = 16 * 7, so m = 16 is a valid power-of-two residue order
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ParamRecommendationWarning)
        return PolocoloParams(p=113, t=3, m=16, R=3, r=2, c=1, d=1, toy=True)


def test_toy_sbox_is_a_permutation():
    prim = Polocolo(_toy_params())
    images = {prim.from_field(prim._sbox(prim.to_field(x))) for x in range(113)}
    assert len(images) == 113
    assert prim._sbox(prim.F.zero()) == prim.F.zero()


def test_toy_roundtrip():
    prim = Polocolo(_toy_params())
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation_inv(prim.permutation(inp)) == inp


def test_low_addition_mds_search():
    M = low_addition_mds_matrix(3, 8, seed=42)
    assert is_mds(M, field=GF(P_BLS12))
    assert M == low_addition_mds_matrix(3, 8, seed=42)   # seeded -> reproducible
    with pytest.raises(ValueError):
        low_addition_mds_matrix(5, 12)   # below the t + ceil(t/2) + t gate minimum


def test_low_addition_mds_search_reaches_paper_budget_t5():
    # The published t = 5..8 matrices come from unseeded runs and cannot be
    # regenerated, but the search strategy must be able to hit the paper's
    # addition budgets (Table 4). For t = 5 the budget (13 additions) equals the
    # structural minimum and a succeeding seed is quick to find; seed 659 is one.
    M = low_addition_mds_matrix(5, 13, seed=659, attempts=1)
    assert is_mds(M, field=GF(P_BLS12))
    assert M == low_addition_mds_matrix(5, 13, seed=659, attempts=1)


# Seeded runs at relaxed budgets for the larger state sizes: the success
# probability at the paper's exact Table 4 budgets (t=6: 17, t=7: 24, t=8: 31)
# is so low that reaching them needs tens of thousands of restarts (the authors
# ran open-ended searches) -- not CI material. A few gates of slack over the
# t + ceil(t/2) + t structural minimum makes seeded runs succeed in milliseconds.
SEARCH_CASES = [
    # (t, additions, seed) -- each seed succeeds on its first attempt
    (6, 21, 3),
    (7, 28, 98),
    (8, 40, 62),
]


@pytest.mark.parametrize("t,additions,seed", SEARCH_CASES, ids=[f"t{t}-add{a}" for t, a, _ in SEARCH_CASES])
def test_low_addition_mds_search_slack_budgets(t, additions, seed):
    M = low_addition_mds_matrix(t, additions, seed=seed, attempts=1)
    # Integer-mode is_mds (minors over ZZ, as for the pinned MDS constants): the
    # field-mode check on a t=8 matrix over a 255-bit prime takes minutes, and
    # no ZZ-nonzero minor of these small entries can be divisible by such a p.
    assert is_mds(M)


def test_init_mat_fallback_warns_and_is_mds():
    # No published matrix exists for t = 2; _init_mat falls back to the randomized
    # low-addition search and flags that the result is not a published constant.
    # _init_mat's budget-escalation loop (additions += t on failure) never fires
    # here: at t = 2 the starting budget (2t + ceil(t/2) + t = 7) succeeds on
    # every attempt -- escalation only matters for larger t, where the success
    # probability at the starting budget collapses (e.g. t = 8 typically
    # escalates twice before finding a matrix).
    with pytest.warns(ParamRecommendationWarning):
        params = PolocoloParams(p=113, t=2, m=16, R=3, r=1, c=1, d=1, kappa=ceil(log2(113))*2, toy=True) # capacity/digest holds 2*kappa bits
    assert is_mds(params.M)


# ---------------------------------------------------------------------------
# 4.5 Misc: validation and warnings
# ---------------------------------------------------------------------------

def test_invalid_state_size():
    prim = Polocolo(POLOCOLO_BLS12_381_SCALAR_T3)
    with pytest.raises(ValueError):
        prim.permutation([prim.F.zero()] * (prim.t + 1))


def test_m_must_divide_p_minus_1():
    with pytest.raises(ValueError):
        PolocoloParams(p=P_BLS12, t=3, m=7, R=6, r=2, c=1, d=1)   # 7 does not divide p-1


def test_sigma_must_be_a_permutation():
    with pytest.raises(ValueError):
        PolocoloParams(p=P_BLS12, t=3, m=4, R=6, sigma=[0, 1, 2, 2], r=2, c=1, d=1)


def test_matrix_shape_is_checked():
    with pytest.raises(ValueError):
        PolocoloParams(p=P_BLS12, t=3, m=1024, R=6, M=[[1, 2], [3, 4]], r=2, c=1, d=1)


def test_recommended_instance_constructs_without_warnings():
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        PolocoloParams(p=P_BLS12, t=3, m=1024, R=6, r=2, c=1, d=1)
    assert not [w for w in caught if issubclass(w.category, ParamRecommendationWarning)]


def test_toy_field_warns():
    with pytest.warns(ParamRecommendationWarning):
        PolocoloParams(p=113, t=3, m=16, R=3, r=2, c=1, d=1, toy=True)


def test_non_recommended_m_warns():
    with pytest.warns(ParamRecommendationWarning):
        PolocoloParams(p=P_BLS12, t=4, m=1024, R=5, r=3, c=1, d=1)   # reference T4; paper says 512
