# test_gmimc2.py
# ---------------------------------------------------------------------------
# Test suite for GMiMC2, parametrized over the named instances in
# instances.py so every recommended instance is covered by the same checks.
#
# Groups:
#   4.1 KATs         -- fixed input/output vectors (permutation + sponge)
#   4.2 Roundtrip    -- permutation_inv undoes permutation (and per-layer)
#   4.3 Consistency  -- determinism, distinct inputs -> distinct outputs, sizes
#   4.4 Algebraic    -- linear layer vs. matrix, derivation vs. pinned instance
#   4.5 Misc         -- validation/errors, warnings, reproducibility
# ---------------------------------------------------------------------------

import warnings

import pytest

from gmimc.hash import GMiMC2Perm, GMiMC2Hash
from gmimc.params import GMiMC2Params
from gmimc.instances import GMIMC2_BN254_T4, GMIMC2_BLS12_T4, GMIMC2_GOLDILOCKS_T8, GMIMC2_GOLDILOCKS_T12, GMIMC2_MERSENNE_T16, GMIMC2_MERSENNE_T24
from utils.matrix import matvecmul
from recommendations import ParamRecommendationWarning

INSTANCES = [
    ("BN254_T4", GMIMC2_BN254_T4),
    ("BLS12_T4", GMIMC2_BLS12_T4),
    ("GOLDILOCKS_T8", GMIMC2_GOLDILOCKS_T8),
    ("GOLDILOCKS_T12", GMIMC2_GOLDILOCKS_T12),
    ("MERSENNE_T16", GMIMC2_MERSENNE_T16),
    ("MERSENNE_T24", GMIMC2_MERSENNE_T24),
]
IDS = [name for name, _ in INSTANCES]

# ---------------------------------------------------------------------------
# 4.1 Known-answer tests
#
# Self-derived vectors: the round constants are deterministically derived from
# (p, t, R) via SHAKE256 inside params, so the outputs are reproducible.
# Regenerated by running the permutation / sponge once and pasting the result.
# No upstream reference vectors are published for this GMiMC-erf instantiation.
# ---------------------------------------------------------------------------

KATS = {
    "BN254_T4": [
        {"input": [0, 1, 2, 3], "output": [3142868953203652013900798594202452880837047414918906747095030874266292989875,
                                        15221442682901908276015225235538097493383451186512385920864741583364059799892,
                                        13360341208732530065928772437867147175213395814073645006965349287864513659758,
                                        9633323678233655977794358888572128941418901557087188293817020346989512066767]},
    ],
    "BLS12_T4": [
        {"input": [0, 1, 2, 3], "output": [12950634327296433590078674419771569707628956897402650376680410924939818707414,
                                        6772715613019528095327681787402161752096123620355795033343682373597908278111,
                                        45246158603402862854190699681601189617425079413051358175827433887042200783683,
                                        27750877161181460416997434907766344064415163323964067588113013468313905329919]},
    ],
    "GOLDILOCKS_T8": [
        {"input": [0, 1, 2, 3, 4, 5 ,6, 7], "output": [18023544793857611469,
                                                    17554502750819567143,
                                                    587971700960806481,
                                                    384201360974850679,
                                                    12097072338262155562,
                                                    13248288725889982036,
                                                    11834834877755945029,
                                                    14516854629177632277]},
    ],
    "GOLDILOCKS_T12": [
        {"input": [0, 1, 2, 3, 4, 5 ,6, 7, 8, 9, 10, 11], "output": [12757343389140009169,
                                                                    9981818749666658780,
                                                                    15390345345507484608,
                                                                    5109798365001041212,
                                                                    1729792435433166669,
                                                                    16777227738805694272,
                                                                    5710321680887175496,
                                                                    11124617642432379009,
                                                                    14170558703498278686,
                                                                    8100177055468022945,
                                                                    6306989437677588676,
                                                                    8460964720081306406]},
    ],
    "MERSENNE_T16": [
        {"input": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
         "output": [1553906753,
                    1240728630,
                    727185454,
                    622732740,
                    1674028771,
                    534183334,
                    223534403,
                    1501104106,
                    1334592794,
                    1680393599,
                    82107231,
                    732296125,
                    1371938347,
                    1089027466,
                    1365075151,
                    50216518]},
    ],
    "MERSENNE_T24": [
        {"input": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
         "output": [2046961707, 
                    972342231, 
                    1598432669, 
                    559237327, 
                    1334252198, 
                    2058250107, 
                    2104345533, 
                    501952010, 
                    2147234755, 
                    1211618386, 
                    1755198768, 
                    853778575, 
                    1141207762, 
                    79465838, 
                    1239429838, 
                    1784167518, 
                    2041479601, 
                    27903012, 
                    100253522, 
                    1712503700, 
                    1255049678, 
                    604276969, 
                    318434845, 
                    358731182]},
    ],
}

KAT_CASES = [
    (name, params, kat)
    for name, params in INSTANCES
    for kat in KATS.get(name, [])
]
KAT_IDS = [
    name if len(KATS.get(name, [])) == 1 else f"{name}-{i}"
    for name, params in INSTANCES
    for i, _ in enumerate(KATS.get(name, []))
]

@pytest.mark.parametrize("name,params,kat", KAT_CASES, ids=KAT_IDS)
def test_permutation_kat(name, params, kat):
    P = GMiMC2Perm(params)
    inp = [P.to_field(x) for x in kat["input"]]
    out = P.permute(inp)
    assert [P.from_field(x) for x in out] == kat["output"]


# ---------------------------------------------------------------------------
# 4.2 Roundtrip (invertibility)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_roundtrip(name, params):
    P = GMiMC2Perm(params)
    inp = [P.F.random_element() for _ in range(P.t)]
    assert P.permute_inv(P.permute(inp)) == inp


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_layer_roundtrip(name, params):
    # Each component layer must be undone by its _inv partner, for every round.
    P = GMiMC2Perm(params)
    inp = [P.F.random_element() for _ in range(P.t)]
    for r in range(P.R):
        assert P.nonlinear_layer_inv(P.nonlinear_layer(inp, r), r) == inp
        assert P.linear_layer_inv(P.linear_layer(inp, r), r) == inp
    assert P._pre_rounds_inv(P._pre_rounds(inp)) == inp
    assert P._post_rounds_inv(P._post_rounds(inp)) == inp


# ---------------------------------------------------------------------------
# 4.3 Consistency
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_deterministic(name, params):
    P = GMiMC2Perm(params)
    inp = [P.F.random_element() for _ in range(P.t)]
    assert P.permute(inp) == P.permute(inp)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_distinct_inputs(name, params):
    P = GMiMC2Perm(params)
    inp1 = [P.F.random_element() for _ in range(P.t)]
    inp2 = [P.F.random_element() for _ in range(P.t)]
    while inp1 == inp2:
        inp2 = [P.F.random_element() for _ in range(P.t)]
    assert P.permute(inp1) != P.permute(inp2)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_output_size(name, params):
    P = GMiMC2Perm(params)
    inp = [P.F.random_element() for _ in range(P.t)]
    assert len(P.permute(inp)) == P.t


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_sponge_output_size(name, params):
    P = GMiMC2Perm(params)
    H = GMiMC2Hash(P, params.sponge)
    data = [P.F.random_element() for _ in range(params.sponge["r"])]
    assert len(H.hash(data, input_len_fixed=True)) == H.sponge.d


# ---------------------------------------------------------------------------
# 4.4 Algebraic / derivation
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_linear_layer_matches_matrix(name, params):
    # GMiMC2's linear layer is the cyclic-shift permutation matrix (not MDS by design).
    P = GMiMC2Perm(params)
    inp = [P.F.random_element() for _ in range(P.t)]
    assert P.linear_layer(inp, 0) == matvecmul(P.M, inp)
    # Cyclic left shift: entry i of the output is entry (i+1) mod t of the input.
    assert P.linear_layer(inp, 0) == inp[1:] + inp[:1]


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_generated_matches_instance(name, params):
    # Rebuilding the params without M / rcons must reproduce the pinned instance.
    derived = GMiMC2Params(p=params.p, t=params.t, R=params.R,
                          sponge=dict(r=params.sponge["r"], c=params.sponge["c"], d=params.sponge["d"]))
    assert derived.M == params.M
    assert derived.rcons == params.rcons


@pytest.mark.skip(reason="_init_rounds is a stub (round number derivation not implemented for GMiMC2)")
@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_rounds_derivation_matches_instance(name, params):
    derived = GMiMC2Params(p=params.p, t=params.t,
                          sponge=dict(r=params.sponge["r"], c=params.sponge["c"], d=params.sponge["d"]))  # R omitted -> _init_rounds
    assert derived.R == params.R


# ---------------------------------------------------------------------------
# 4.5 Misc: validation, warnings, reproducibility
# ---------------------------------------------------------------------------

def test_invalid_state_size():
    P = GMiMC2Perm(GMIMC2_BN254_T4)
    with pytest.raises(ValueError):
        P.permute([P.F.zero()] * (P.t + 1))


def test_toy_field_warns():
    with pytest.warns(ParamRecommendationWarning):
        GMiMC2Params(p=101, t=3, R=5, sponge=dict(r=2, c=1, d=1), toy=True)  # tiny field


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_recommended_instance_no_warning(name, params):
    with warnings.catch_warnings():
        warnings.simplefilter("error", ParamRecommendationWarning)
        GMiMC2Params(p=params.p, t=params.t, R=params.R,
                     sponge=dict(r=params.sponge["r"], c=params.sponge["c"], d=params.sponge["d"]))


def test_constants_reproducible():
    # Same parameters -> identical derived constants and matrix.
    a = GMiMC2Params(p=GMIMC2_BN254_T4.p, t=4, R=10, sponge=dict(r=3, c=1, d=1))
    b = GMiMC2Params(p=GMIMC2_BN254_T4.p, t=4, R=10, sponge=dict(r=3, c=1, d=1))
    assert a.rcons == b.rcons
    assert a.M == b.M
