# test_gmimc.py
# ---------------------------------------------------------------------------
# Test suite for GMiMC (erf variant), parametrized over the named instances in
# instances.py so every recommended instance is covered by the same checks.
#
# Groups:
#   4.1 KATs         -- fixed input/output vectors (permutation + sponge)
#   4.2 Roundtrip    -- permutation_inv undoes permutation (and per-layer)
#   4.3 Consistency  -- determinism, distinct inputs -> distinct outputs, sizes
#   4.4 Algebraic    -- linear layer vs. matrix, derivation vs. pinned instance
#   4.5 Misc         -- validation/errors, warnings, reproducibility
# ---------------------------------------------------------------------------

import warnings

import pytest

from gmimc.hash import GMiMC
from gmimc.params import GMiMCParams
from gmimc.instances import GMIMC_BN254_T3, GMIMC_BLS12_T3
from utils.matrix import matvecmul
from recommendations import ParamRecommendationWarning

INSTANCES = [
    ("BN254_T3", GMIMC_BN254_T3),
    ("BLS12_T3", GMIMC_BLS12_T3),
]
IDS = [name for name, _ in INSTANCES]

# ---------------------------------------------------------------------------
# 4.1 Known-answer tests
#
# Self-derived vectors: the round constants are deterministically derived from
# (p, t, R) via SHAKE256 inside params, so the outputs are reproducible.
# Regenerated by running the permutation / sponge once and pasting the result.
# No upstream reference vectors are published for this GMiMC-erf instantiation.
# ---------------------------------------------------------------------------

KATS = {
    "BN254_T3": [
        {"input": [0, 1, 2], "output": [0x18d5f79d07d9a5b120d1949af661b37e6ac24ffd7992a8f7ebb83c8284b038bc,
                                        0x0dc2711f096e6f74ce1036baaf169a06c618e364eae70776c1db8ddd27b6869b,
                                        0x08d83f6a59c6bf14371f393eb13a10c3a80e6ec5d6e471b306c574237b03b5ad]},
        {"input": [0, 0, 0], "output": [0x15786830a9a1ed7ed344bd97a300d4a46961db6c49e6cbefb832b656c40bb331,
                                        0x1176103d11445c7585bdef3d6fa19834d575c72b1f76cc4afb3e066216801fc0,
                                        0x0d3ad3d767359d5a883884093fbbb15353cae474a9525222e8073bf97c1d923c]},
    ],
    "BLS12_T3": [
        {"input": [0, 1, 2], "output": [0x55fbfcfe1148996a851e2e5591464c22f7cfef1bcb3691e3f088dfd53acfe4cd,
                                        0x4909cf076af6168aec10979d5cfdc004537999e376940ce51a0469a80b3ff64a,
                                        0x1543b6b5f331ecb987042f72a717ba5dff2226cf5797581eedb062593105fbdd]},
        {"input": [0, 0, 0], "output": [0x4883bfe5f65f1c9404bab42f08db5adae72c3dba87ca9bf690cf4f2be6f91298,
                                        0x08a7d867b99143266794dea8572d3d976817896190c434d705b85d91ac6ccde4,
                                        0x2213aba302d15d33d6e8202d75706297185d6813aa2e2e3da89925fcd120c315]},
    ],
}

KAT_CASES = [
    (name, params, kat)
    for name, params in INSTANCES
    for kat in KATS.get(name, [])
]
KAT_IDS = [
    name if len(KATS.get(name, [])) == 1 else f"{name}-{i}"
    for name, params in INSTANCES
    for i, _ in enumerate(KATS.get(name, []))
]


@pytest.mark.parametrize("name,params,kat", KAT_CASES, ids=KAT_IDS)
def test_permutation_kat(name, params, kat):
    prim = GMiMC(params)
    inp = [prim.to_field(x) for x in kat["input"]]
    out = prim.permutation(inp)
    assert [prim.from_field(x) for x in out] == kat["output"]


# Sponge KATs: inputs chosen to exercise pad_zero (empty, shorter than the rate,
# exactly one block, not a multiple of the rate, two full blocks).
SPONGE_KATS = {
    "BN254_T3": [
        {"input": [],           "output": [0x0]},
        {"input": [1],          "output": [0x24601c107b7629cad8019f4c835b605fb71512ec32712e492be3d6923e666f51]},
        {"input": [0, 1],       "output": [0x18d5f79d07d9a5b120d1949af661b37e6ac24ffd7992a8f7ebb83c8284b038bc]},
        {"input": [0, 1, 2],    "output": [0x2721ef7879e9ed0b176a16ee7a6097cd5ff4ff41e5d6ea6af36c22e602f00320]},
        {"input": [0, 1, 2, 3], "output": [0x2c3e07e802f213733f71c51a9c122da299ea96d89de81eb39ca55d1480022330]},
    ],
    "BLS12_T3": [
        {"input": [],           "output": [0x0]},
        {"input": [1],          "output": [0x292bbcc3457b87e89af3458a55170903e78e080f479aa095b2831498a04039d9]},
        {"input": [0, 1],       "output": [0x55fbfcfe1148996a851e2e5591464c22f7cfef1bcb3691e3f088dfd53acfe4cd]},
        {"input": [0, 1, 2],    "output": [0x562e29109b259ca25742115ea711679ab7a71b8d2660d8128b85c6e87476594f]},
        {"input": [0, 1, 2, 3], "output": [0x738e975ba06b6f11b4bf673653e75e1e2d1ec5b4d2e18b8d88ebbfa6f52b7f09]},
    ],
}

SPONGE_KAT_CASES = [
    (name, params, kat)
    for name, params in INSTANCES
    for kat in SPONGE_KATS.get(name, [])
]
SPONGE_KAT_IDS = [
    name if len(SPONGE_KATS.get(name, [])) == 1 else f"{name}-{i}"
    for name, params in INSTANCES
    for i, _ in enumerate(SPONGE_KATS.get(name, []))
]


@pytest.mark.parametrize("name,params,kat", SPONGE_KAT_CASES, ids=SPONGE_KAT_IDS)
def test_sponge_kat(name, params, kat):
    prim = GMiMC(params)
    inp = [prim.to_field(x) for x in kat["input"]]
    out = prim.hash_sponge(inp)
    assert [prim.from_field(x) for x in out] == kat["output"]


# ---------------------------------------------------------------------------
# 4.2 Roundtrip (invertibility)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_roundtrip(name, params):
    prim = GMiMC(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation_inv(prim.permutation(inp)) == inp


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_layer_roundtrip(name, params):
    # Each component layer must be undone by its _inv partner, for every round.
    prim = GMiMC(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    for r in range(prim.R):
        assert prim.nonlinear_layer_inv(prim.nonlinear_layer(inp, r), r) == inp
        assert prim.linear_layer_inv(prim.linear_layer(inp, r), r) == inp
    assert prim._pre_rounds_inv(prim._pre_rounds(inp)) == inp
    assert prim._post_rounds_inv(prim._post_rounds(inp)) == inp


# ---------------------------------------------------------------------------
# 4.3 Consistency
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_deterministic(name, params):
    prim = GMiMC(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation(inp) == prim.permutation(inp)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_distinct_inputs(name, params):
    prim = GMiMC(params)
    inp1 = [prim.F.random_element() for _ in range(prim.t)]
    inp2 = [prim.F.random_element() for _ in range(prim.t)]
    while inp1 == inp2:
        inp2 = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.permutation(inp1) != prim.permutation(inp2)


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_permutation_output_size(name, params):
    prim = GMiMC(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert len(prim.permutation(inp)) == prim.t


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_sponge_output_size(name, params):
    prim = GMiMC(params)
    data = [prim.F.random_element() for _ in range(prim.sponge.r)]
    assert len(prim.hash_sponge(data)) == prim.sponge.d


# ---------------------------------------------------------------------------
# 4.4 Algebraic / derivation
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_linear_layer_matches_matrix(name, params):
    # GMiMC's linear layer is the cyclic-shift permutation matrix (not MDS by design).
    prim = GMiMC(params)
    inp = [prim.F.random_element() for _ in range(prim.t)]
    assert prim.linear_layer(inp, 0) == matvecmul(prim.M, inp)
    # Cyclic left shift: entry i of the output is entry (i+1) mod t of the input.
    assert prim.linear_layer(inp, 0) == inp[1:] + inp[:1]


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_generated_matches_instance(name, params):
    # Rebuilding the params without M / rcons must reproduce the pinned instance.
    derived = GMiMCParams(p=params.p, t=params.t, R=params.R,
                          r=params.sponge.r, c=params.sponge.c, d=params.sponge.d)
    assert derived.M == params.M
    assert derived.rcons == params.rcons


@pytest.mark.skip(reason="_init_rounds is a stub (round number derivation not implemented for GMiMC)")
@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_rounds_derivation_matches_instance(name, params):
    derived = GMiMCParams(p=params.p, t=params.t,
                          r=params.sponge.r, c=params.sponge.c, d=params.sponge.d)  # R omitted -> _init_rounds
    assert derived.R == params.R


# ---------------------------------------------------------------------------
# 4.5 Misc: validation, warnings, reproducibility
# ---------------------------------------------------------------------------

def test_invalid_state_size():
    prim = GMiMC(GMIMC_BN254_T3)
    with pytest.raises(ValueError):
        prim.permutation([prim.F.zero()] * (prim.t + 1))


def test_alpha_must_be_permutation():
    # An explicit alpha not coprime with p-1 must be rejected by params.
    with pytest.raises(ValueError):
        GMiMCParams(p=GMIMC_BN254_T3.p, t=3, R=5, alpha=2, r=2, c=1, d=1)


def test_toy_field_warns():
    with pytest.warns(ParamRecommendationWarning):
        GMiMCParams(p=101, t=3, R=5, r=2, c=1, d=1, toy=True)  # tiny field


@pytest.mark.parametrize("name,params", INSTANCES, ids=IDS)
def test_recommended_instance_no_warning(name, params):
    with warnings.catch_warnings():
        warnings.simplefilter("error", ParamRecommendationWarning)
        GMiMCParams(p=params.p, t=params.t, R=params.R,
                    r=params.sponge.r, c=params.sponge.c, d=params.sponge.d)


def test_constants_reproducible():
    # Same parameters -> identical derived constants and matrix.
    a = GMiMCParams(p=GMIMC_BLS12_T3.p, t=3, R=10, r=2, c=1, d=1)
    b = GMiMCParams(p=GMIMC_BLS12_T3.p, t=3, R=10, r=2, c=1, d=1)
    assert a.rcons == b.rcons
    assert a.M == b.M
