import hashlib

from utils import circulant


class ReinforcedConcreteParams:
    INIT_SHAKE = b"ReinforcedConcrete"

    def __init__(
        self,
        p:           int,
        alpha:       int,
        pre_rounds:  int,
        bars_rounds: int,
        post_rounds: int,
        si:          list[int],
        lut:         list[int],
        ab:          list[int],
        state_size:  int = 3,                                # only suggested state size, DO NOT CHANGE
        mds_matrix:  list[list[int]] = circulant([2, 1, 1]), # only suggested matrix, DO NOT CHANGE
        digest_size: int = 1,                                # only suggested digest size, DO NOT CHANGE
        alpha_inv:   int = None,                             # alpha^{-1} mod (p-1); computed as fallback if absent
    ):
        """
        Parameters
        ----------
        p           : field characteristic (prime)
        alpha       : power-map exponent for the first state element in Bricks
        pre_rounds  : number of Bricks+Concrete rounds before the Bars layer(s)
        bars_rounds : number of Bars+Concrete rounds in the middle (after pre_rounds, before post_rounds)
        post_rounds : number of Bricks+Concrete rounds after the Bars layer(s)
        si          : mixed-radix base sequence for Bars decompose/compose
        lut         : lookup table applied to each digit in Bars
        ab          : [a1, a2, b1, b2] — Bricks polynomial coefficients
        alpha_inv   : alpha^{-1} mod (p-1); pass from Field.alpha_inv to avoid computing for large primes
        """
        assert len(lut) <= 0xFFFF
        assert len(ab) == 4

        self.state_size   = state_size
        self.mds_matrix   = mds_matrix
        self.digest_size  = digest_size
        self.p            = p
        self.alpha        = alpha
        self.alpha_inv    = alpha_inv
        self.pre_rounds   = pre_rounds
        self.bars_rounds  = bars_rounds
        self.post_rounds  = post_rounds
        self.total_rounds = pre_rounds + bars_rounds + post_rounds
        self.si           = list(si)

        # ab = [a1, a2, b1, b2] — stored as plain ints
        self.a_coeffs = [ab[0], ab[1]]
        self.b_coeffs = [ab[2], ab[3]]

        self.lut     = self._pad_lut(lut, si)
        self.lut_inv = self._invert_lut(self.lut)
        self.round_constants = self._instantiate_rc(self._init_shake())

    # ------------------------------------------------------------------

    def _init_shake(self) -> "_ByteReader":
        num_bits = self.p.bit_length()
        n_bytes  = (num_bits + 7) // 8

        shake = hashlib.shake_128()
        shake.update(self.INIT_SHAKE)
        shake.update(self.p.to_bytes(n_bytes, "little"))

        return _ByteReader(shake.digest(100_000), n_bytes, self.p, num_bits)

    def _instantiate_rc(self, reader: "_ByteReader") -> list[list[int]]:
        return [
            [reader.read() for _ in range(self.state_size)]
            for _ in range(self.total_rounds + 1)
        ]

    @staticmethod
    def _pad_lut(lut: list[int], si: list[int]) -> list[int]:
        out    = list(lut)
        max_si = max(si)
        for i in range(len(lut), max_si):
            out.append(i)
        return out

    @staticmethod
    def _invert_lut(lut: list[int]) -> list[int]:
        inv = [0] * len(lut)
        for i, v in enumerate(lut):
            inv[v] = i
        return inv


class _ByteReader:
    """Sequential reader over a pre-generated byte string.

    Mirrors field_element_from_shake in the Rust reference, reads ceil(NUM_BITS/8)
    bytes at a time, masks the top bits of the last byte to stay within [0, 2^NUM_BITS),
    then rejects if the value >= p (same logic as ff::PrimeField::from_repr).
    See https://extgit.isec.tugraz.at/krypto/zkfriendlyhashzoo/-/blob/master/plain_impls/src/fields/utils.rs.
    """

    def __init__(self, data: bytes, n_bytes: int, p: int, num_bits: int):
        self._data    = data
        self._pos     = 0
        self._n_bytes = n_bytes
        self._p       = p
        mod_          = num_bits % 8
        self._mask    = ((1 << mod_) - 1) if mod_ != 0 else 0xFF

    def read(self) -> int:
        while True:
            raw          = bytearray(self._data[self._pos : self._pos + self._n_bytes])
            self._pos   += self._n_bytes
            raw[-1]     &= self._mask          # zero out bits above NUM_BITS
            val          = int.from_bytes(raw, "little")
            if val < self._p:
                return val
